{{- if .Values.artifactHub.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axisml.fullname" . }}-artifact-hub
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "artifact-hub") | nindent 4 }}
data:
  config.yaml: |
    database:
      host: {{ include "axisml.databaseHost" . }}
      port: {{ include "axisml.databasePort" . }}
      name: {{ .Values.database.auth.database }}
      user: {{ .Values.database.auth.username }}
      sslmode: {{ .Values.database.sslMode | default "disable" }}
    log:
      level: {{ .Values.artifactHub.log.level | default "info" }}
      format: {{ .Values.artifactHub.log.format | default "json" }}
    oci:
      endpoint: {{ .Values.artifactHub.storage.oci.endpoint }}
      admin_user: {{ .Values.artifactHub.storage.oci.adminSecretRef.username | default "admin" }}
{{- end }}
