{{- if .Values.artifactHub.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-artifact-hub
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "artifact-hub") | nindent 4 }}
{{- end }}
