// Command openapi-gen renders the complete standalone OpenAPI contract from
// the three System component contracts plus the routes owned by the assembly.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"

	arthubspec "github.com/axisml/axisml/axisml-system/artifact-hub/pkg/apispec"
	clusterspec "github.com/axisml/axisml/axisml-system/cluster-manager/pkg/apispec"
	computespec "github.com/axisml/axisml/axisml-system/compute-service/pkg/apispec"
	"sigs.k8s.io/yaml"
)

const defaultVersion = "0.0.0-dev"

var assemblyPaths = map[string]bool{
	"/healthz": true,
	"/readyz":  true,
}

func main() {
	out := flag.String("o", "docs/apis/standalone.yaml", "canonical spec output path")
	embed := flag.String("embed", "openapi.gen.yaml", "runtime embed copy output path")
	version := flag.String("version", defaultVersion, "info.version field")
	flag.Parse()

	doc := standaloneDocument(*version)
	for _, raw := range [][]byte{clusterspec.Document(), computespec.Document(), arthubspec.Document()} {
		src, err := parseDocument(raw)
		if err != nil {
			fail("parse system spec: %v", err)
		}
		if err := foldOne(doc, src); err != nil {
			fail("fold system spec: %v", err)
		}
	}
	body, err := yaml.Marshal(doc)
	if err != nil {
		fail("marshal: %v", err)
	}
	data := append([]byte("# Code generated by axisml-standalone/cmd/openapi-gen. DO NOT EDIT.\n# Regenerate with: make api-docs-gen\n"), body...)
	for _, path := range []string{*out, *embed} {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fail("mkdir %s: %v", path, err)
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			fail("write %s: %v", path, err)
		}
		fmt.Fprintf(os.Stderr, "wrote %s\n", path)
	}
}

func parseDocument(data []byte) (map[string]any, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	return doc, nil
}

func standaloneDocument(version string) map[string]any {
	return map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":   "AxisML Standalone API",
			"version": version,
			"description": "Complete HTTP surface of the AxisML standalone distribution: " +
				"Cluster Manager, Compute Service and Artifact Hub on one server with the Docker runtime.",
		},
		"servers": []any{map[string]any{"url": "/", "description": "Same-origin (axisml-standalone)"}},
		"tags": []any{
			map[string]any{"name": "Health", "description": "Liveness and readiness probes."},
		},
		"paths": map[string]any{
			"/healthz": probePath("Liveness probe", "healthz", map[string]any{"200": stringResponse("ok")}),
			"/readyz": probePath("Readiness probe", "readyz", map[string]any{
				"200": stringResponse("ok"), "503": stringResponse("dependency not yet ready"),
			}),
		},
		"components": map[string]any{"schemas": map[string]any{}},
	}
}

func probePath(summary, operationID string, responses map[string]any) map[string]any {
	return map[string]any{"get": map[string]any{
		"tags": []any{"Health"}, "summary": summary, "operationId": operationID, "responses": responses,
	}}
}

func stringResponse(description string) map[string]any {
	return map[string]any{"description": description, "content": map[string]any{
		"text/plain": map[string]any{"schema": map[string]any{"type": "string"}},
	}}
}

func foldOne(dst, src map[string]any) error {
	dstSchemas := nestedMap(dst, "components", "schemas")
	for name, schema := range nestedMap(src, "components", "schemas") {
		if existing, found := dstSchemas[name]; found {
			if !reflect.DeepEqual(existing, schema) {
				return fmt.Errorf("schema %q has divergent definitions", name)
			}
			continue
		}
		dstSchemas[name] = schema
	}
	dstPaths := nestedMap(dst, "paths")
	for path, item := range nestedMap(src, "paths") {
		if assemblyPaths[path] {
			continue
		}
		if _, found := dstPaths[path]; found {
			return fmt.Errorf("path %q already present", path)
		}
		dstPaths[path] = item
	}
	mergeTags(dst, src)
	return nil
}

func nestedMap(root map[string]any, keys ...string) map[string]any {
	current := root
	for _, key := range keys {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	return current
}

func mergeTags(dst, src map[string]any) {
	dstTags, _ := dst["tags"].([]any)
	have := map[string]bool{}
	for _, raw := range dstTags {
		if tag, ok := raw.(map[string]any); ok {
			if name, ok := tag["name"].(string); ok {
				have[name] = true
			}
		}
	}
	for _, raw := range asSlice(src["tags"]) {
		tag, _ := raw.(map[string]any)
		name, _ := tag["name"].(string)
		if name != "" && !have[name] {
			dstTags = append(dstTags, raw)
			have[name] = true
		}
	}
	dst["tags"] = dstTags
}

func asSlice(value any) []any {
	items, _ := value.([]any)
	return items
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "openapi-gen: "+format+"\n", args...)
	os.Exit(1)
}
