DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS experiments;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;
