{{- if and .Values.operators.enabled .Values.operators.mlserviceOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-mlservice-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "mlservice-operator") | nindent 4 }}
{{- end }}
