{{- if .Values.artifacts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axisml.fullname" . }}-artifacts
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "artifacts") | nindent 4 }}
spec:
  type: {{ .Values.artifacts.service.type }}
  ports:
    - port: {{ .Values.artifacts.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "axisml.componentSelectorLabels" (dict "context" . "component" "artifacts") | nindent 4 }}
{{- end }}
