{{- if .Values.artifacts.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-artifacts
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "artifacts") | nindent 4 }}
{{- end }}
