// openapi-gen renders an OpenAPI 3.0.3 description of the axisml-core
// composition surface to axisml-lite/docs/apis/axisml-core.yaml.
//
// axisml-core composes the three System modules (Cluster Manager + Compute
// Service + Artifact Hub) onto one HTTP server. Their per-resource request /
// response contracts are owned and generated by the System layer
// (axisml-system/docs/apis/{cluster-manager,compute-service,artifact-hub}.yaml,
// per design §5: "OpenAPI DTOs are generated and maintained by the System
// components") and are identical here — only the base URL differs. This spec
// therefore documents the surface axisml-core uniquely OWNS on top of those
// modules: the liveness/readiness probes and the aggregate capability document.
//
// Run from the component root:
//
//	go run ./cmd/openapi-gen -o ../../docs/apis/axisml-core.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/axisml/axisml/axisml-lite/axisml-core/internal/core"
	"github.com/axisml/axisml/pkg/openapigen"
)

const defaultVersion = "0.0.0-dev"

const (
	tagCapabilities = "Capabilities"
	tagHealth       = "Health"
)

func main() {
	out := flag.String("o", "../../docs/apis/axisml-core.yaml", "output path")
	v := flag.String("version", defaultVersion, "info.version field")
	flag.Parse()

	doc := buildDocument(*v)
	data, err := openapigen.MarshalYAML(doc)
	if err != nil {
		fail("marshal: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	if err := os.WriteFile(*out, data, 0o644); err != nil {
		fail("write: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "openapi-gen: "+format+"\n", args...)
	os.Exit(1)
}

func buildDocument(version string) *openapigen.Document {
	g := openapigen.New(openapigen.Options{
		// The capability DTO lives in the flat internal/core package, so map it to
		// an empty prefix and the schema name equals the Go type name verbatim.
		PackageNamer: func(pkg string) (string, bool) {
			if strings.HasSuffix(pkg, "/axisml-lite/axisml-core/internal/core") {
				return "", true
			}
			return "", false
		},
	})

	g.Register("Capabilities", core.Capabilities{}, openapigen.ResponseMode)

	tags := []openapigen.TagEntry{
		{Name: tagCapabilities, Description: "Aggregate deployment-form capability document — the three System modules' per-form documents folded under their component key (design §5.5)."},
		{Name: tagHealth, Description: "Liveness and readiness probes."},
	}

	paths := map[string]openapigen.PathItem{}

	paths["/healthz"] = openapigen.PathItem{Get: &openapigen.Operation{
		Tags: []string{tagHealth}, Summary: "Liveness probe", OperationID: "healthz",
		Responses: map[string]openapigen.Response{"200": openapigen.StringResp("ok")},
	}}
	paths["/readyz"] = openapigen.PathItem{Get: &openapigen.Operation{
		Tags: []string{tagHealth}, Summary: "Readiness probe", OperationID: "readyz",
		Responses: map[string]openapigen.Response{
			"200": openapigen.StringResp("ok"),
			"503": openapigen.StringResp("dependency not yet ready"),
		},
	}}
	paths["/api/v1/capabilities"] = openapigen.PathItem{Get: &openapigen.Operation{
		Tags: []string{tagCapabilities}, Summary: "Get the aggregate capability document", OperationID: "getCapabilities",
		Responses: map[string]openapigen.Response{"200": openapigen.JSONResp("Aggregate capability document.", "Capabilities")},
	}}

	return &openapigen.Document{
		OpenAPI: "3.0.3",
		Info: openapigen.Info{
			Title:   "AxisML Core API",
			Version: version,
			Description: "Composition surface of axisml-core (AxisML Lite single-host form): " +
				"Cluster Manager + Compute Service + Artifact Hub served on one HTTP server, " +
				"plus the Standalone Docker runtime. The per-resource contracts are identical to " +
				"the System APIs (axisml-system/docs/apis/{cluster-manager,compute-service,artifact-hub}.yaml) " +
				"and reachable at the same paths on this server; this document covers the probes and the " +
				"Lite-owned aggregate capability endpoint.",
		},
		Servers: []openapigen.ServerEntry{{URL: "/", Description: "Same-origin (axisml-core)"}},
		Tags:    tags,
		Paths:   paths,
		Components: openapigen.ComponentsBlock{
			Schemas: g.Schemas(),
		},
	}
}
