//go:build !ignore_autogenerated

// Code generated by deepcopy. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *ElasticQuota) DeepCopyInto(out *ElasticQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ElasticQuota.
func (in *ElasticQuota) DeepCopy() *ElasticQuota {
	if in == nil {
		return nil
	}
	out := new(ElasticQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ElasticQuota.
func (in *ElasticQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticQuotaSpec) DeepCopyInto(out *ElasticQuotaSpec) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy creates a deep copy of ElasticQuotaSpec.
func (in *ElasticQuotaSpec) DeepCopy() *ElasticQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticQuotaStatus) DeepCopyInto(out *ElasticQuotaStatus) {
	*out = *in
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy creates a deep copy of ElasticQuotaStatus.
func (in *ElasticQuotaStatus) DeepCopy() *ElasticQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *ElasticQuotaList) DeepCopyInto(out *ElasticQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ElasticQuotaList.
func (in *ElasticQuotaList) DeepCopy() *ElasticQuotaList {
	if in == nil {
		return nil
	}
	out := new(ElasticQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a runtime.Object copy of ElasticQuotaList.
func (in *ElasticQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
