/* eslint-disable */
// AUTO-GENERATED by scripts/gen-mock.mjs from ../../../docs/apis/platform.yaml.
// DO NOT EDIT. Regenerate with: pnpm run gen:mock (or make -C axisml-platform frontend-gen-mock).
//
// Whole-object examples lifted from the OpenAPI spec's component schemas, keyed
// by schema name. These back the in-browser mock (VITE_USE_MOCK_API); the
// authoring lives on the Go DTOs, so fixtures stay in lock-step with the contract.

export const examples: Record<string, unknown> = {
  "ArtifactDefinition": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "ResNet-50 图像分类模型。",
    "displayName": "ResNet-50",
    "id": "1f2e3d4c-5b6a-7980-abcd-ef0123456789",
    "kind": "model",
    "labels": {
      "team": "vision"
    },
    "name": "resnet50",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "ArtifactDefinitionCreateRequest": {
    "description": "ResNet-50 图像分类模型。",
    "displayName": "ResNet-50",
    "labels": {
      "team": "vision"
    },
    "name": "resnet50"
  },
  "ArtifactDefinitionList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "ResNet-50 图像分类模型。",
        "displayName": "ResNet-50",
        "id": "1f2e3d4c-5b6a-7980-abcd-ef0123456789",
        "kind": "model",
        "labels": {
          "team": "vision"
        },
        "name": "resnet50",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "ArtifactDefinitionPatchRequest": {
    "description": "更新后的定义描述。",
    "displayName": "ResNet-50 (v2)"
  },
  "ArtifactRef": {
    "kind": "model",
    "name": "resnet50",
    "version": "1.4.0"
  },
  "ArtifactResolveResponse": {
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
    "expiresAt": "2026-06-28T09:30:00Z",
    "pullCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "pull-token"
    },
    "storageKind": "oci",
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0"
  },
  "ArtifactUpdateRequest": {
    "description": "更新后的版本描述。",
    "displayName": "ResNet-50 v1.4.0 (校准)",
    "labels": {
      "team": "vision"
    }
  },
  "Backend": {
    "engine": "pytorchjob",
    "name": "native"
  },
  "Condition": {
    "lastTransitionTime": "2026-06-28T09:30:00Z",
    "message": "All worker replicas are ready.",
    "reason": "AllReplicasReady",
    "status": "True",
    "type": "Ready"
  },
  "ConfigMapInit": {
    "name": "shared-config",
    "sourceConfigMapRef": {
      "name": "shared-config",
      "namespace": "axisml-system"
    }
  },
  "ConfigMapSourceRef": {
    "name": "shared-config",
    "namespace": "axisml-system"
  },
  "EnvVar": {
    "name": "NCCL_DEBUG",
    "value": "INFO"
  },
  "Event": {
    "count": 1,
    "firstTimestamp": "2026-06-28T09:00:00Z",
    "involvedObject": {
      "kind": "Pod",
      "name": "resnet-train-7-worker-0",
      "namespace": "axisml-team-vision"
    },
    "lastTimestamp": "2026-06-28T09:00:00Z",
    "message": "Successfully assigned resnet-train-7-worker-0 to gpu-node-03.",
    "reason": "Scheduled",
    "source": "default-scheduler",
    "type": "Normal"
  },
  "EventList": {
    "count": 1,
    "items": [
      {
        "count": 1,
        "firstTimestamp": "2026-06-28T09:00:00Z",
        "involvedObject": {
          "kind": "Pod",
          "name": "resnet-train-7-worker-0",
          "namespace": "axisml-team-vision"
        },
        "lastTimestamp": "2026-06-28T09:00:00Z",
        "message": "Successfully assigned resnet-train-7-worker-0 to gpu-node-03.",
        "reason": "Scheduled",
        "source": "default-scheduler",
        "type": "Normal"
      }
    ]
  },
  "Experiment": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "在中文语料上微调 BERT 的训练实验。",
    "displayName": "BERT 微调实验",
    "id": "d4f8a1b2-3c5e-4a7b-9c0d-1e2f3a4b5c6d",
    "labels": {
      "team": "nlp"
    },
    "name": "bert-finetune",
    "namespace": "team-nlp",
    "owner": "zhang.san",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "bert-base",
          "version": "2.1.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "kubeflow-trainer"
      },
      "poolName": "gpu-a100",
      "quota": "team-nlp",
      "roles": [
        {
          "name": "worker",
          "replicas": 2,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--lr",
              "0.001",
              "--epochs",
              "10",
              "--batch-size",
              "64"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "WANDB_MODE",
                "value": "offline"
              }
            ],
            "image": "registry.axisml.io/training/bert:2.1.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    },
    "tenantName": "team-nlp",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "ExperimentCreateRequest": {
    "description": "在中文语料上微调 BERT 的训练实验。",
    "displayName": "BERT 微调实验",
    "labels": {
      "team": "nlp"
    },
    "name": "bert-finetune",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "bert-base",
          "version": "2.1.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "kubeflow-trainer"
      },
      "poolName": "gpu-a100",
      "quota": "team-nlp",
      "roles": [
        {
          "name": "worker",
          "replicas": 2,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--lr",
              "0.001",
              "--epochs",
              "10",
              "--batch-size",
              "64"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "WANDB_MODE",
                "value": "offline"
              }
            ],
            "image": "registry.axisml.io/training/bert:2.1.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    }
  },
  "ExperimentList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "在中文语料上微调 BERT 的训练实验。",
        "displayName": "BERT 微调实验",
        "id": "d4f8a1b2-3c5e-4a7b-9c0d-1e2f3a4b5c6d",
        "labels": {
          "team": "nlp"
        },
        "name": "bert-finetune",
        "namespace": "team-nlp",
        "owner": "zhang.san",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "spec": {
          "artifacts": [
            {
              "kind": "model",
              "name": "bert-base",
              "version": "2.1.0"
            }
          ],
          "backend": {
            "engine": "pytorchjob",
            "name": "kubeflow-trainer"
          },
          "poolName": "gpu-a100",
          "quota": "team-nlp",
          "roles": [
            {
              "name": "worker",
              "replicas": 2,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--lr",
                  "0.001",
                  "--epochs",
                  "10",
                  "--batch-size",
                  "64"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "WANDB_MODE",
                    "value": "offline"
                  }
                ],
                "image": "registry.axisml.io/training/bert:2.1.0",
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                }
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "ttlSecondsAfterFinished": 3600
          },
          "unitName": "a100-2x"
        },
        "tenantName": "team-nlp",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "ExperimentPatchRequest": {
    "description": "更新后的描述。",
    "displayName": "BERT 微调实验 (v2)"
  },
  "HealthStatus": {
    "components": {
      "artifact-hub": "ok",
      "compute-service": "ok",
      "database": "ok"
    },
    "status": "ok"
  },
  "Image": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "包含 PyTorch 2.3 与 CUDA 12 的训练镜像。",
    "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b",
    "displayName": "PyTorch Training 2.3.0",
    "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
    "name": "pytorch-train",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "readyAt": "2026-06-28T09:30:00Z",
    "sizeBytes": 5368709120,
    "source": "dockerPush",
    "status": "Ready",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z",
    "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0",
    "version": "2.3.0"
  },
  "ImageCompleteRequest": {
    "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b"
  },
  "ImageInitiateRequest": {
    "description": "包含 PyTorch 2.3 与 CUDA 12 的训练镜像。",
    "displayName": "PyTorch Training 2.3.0",
    "source": "dockerPush",
    "spec": {
      "purpose": "training"
    },
    "version": "2.3.0"
  },
  "ImageInitiateResponse": {
    "expiresAt": "2026-06-28T09:30:00Z",
    "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
    "storageKind": "oci",
    "uploadCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "upload-token"
    },
    "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0"
  },
  "ImageList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "包含 PyTorch 2.3 与 CUDA 12 的训练镜像。",
        "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b",
        "displayName": "PyTorch Training 2.3.0",
        "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
        "name": "pytorch-train",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "readyAt": "2026-06-28T09:30:00Z",
        "sizeBytes": 5368709120,
        "source": "dockerPush",
        "status": "Ready",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z",
        "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0",
        "version": "2.3.0"
      }
    ],
    "partial": false
  },
  "ImagePullSecretInit": {
    "name": "registry-pull",
    "sourceSecretRef": {
      "name": "registry-pull",
      "namespace": "axisml-system"
    }
  },
  "InitResources": {
    "configMaps": [
      {
        "name": "shared-config",
        "sourceConfigMapRef": {
          "name": "shared-config",
          "namespace": "axisml-system"
        }
      }
    ],
    "imagePullSecrets": [
      {
        "name": "registry-pull",
        "sourceSecretRef": {
          "name": "registry-pull",
          "namespace": "axisml-system"
        }
      }
    ],
    "secrets": [
      {
        "name": "wandb-api-key",
        "sourceSecretRef": {
          "name": "wandb-api-key",
          "namespace": "axisml-system"
        },
        "type": "Opaque"
      }
    ],
    "serviceAccounts": [
      {
        "imagePullSecrets": [
          "registry-pull"
        ],
        "name": "trainer"
      }
    ]
  },
  "Job": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "ImageNet 上的 ResNet-50 分布式训练任务。",
    "displayName": "ResNet-50 训练",
    "id": "8c1f4e22-2b7a-4c0e-9b1d-7f3a2e5c9a10",
    "labels": {
      "team": "vision"
    },
    "name": "resnet-train",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "resnet50",
          "version": "1.4.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "poolName": "gpu-a100",
      "quota": "team-vision",
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    },
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "JobCreateRequest": {
    "description": "ImageNet 上的 ResNet-50 分布式训练任务。",
    "displayName": "ResNet-50 训练",
    "labels": {
      "team": "vision"
    },
    "name": "resnet-train",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "resnet50",
          "version": "1.4.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "poolName": "gpu-a100",
      "quota": "team-vision",
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    }
  },
  "JobList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "ImageNet 上的 ResNet-50 分布式训练任务。",
        "displayName": "ResNet-50 训练",
        "id": "8c1f4e22-2b7a-4c0e-9b1d-7f3a2e5c9a10",
        "labels": {
          "team": "vision"
        },
        "name": "resnet-train",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "spec": {
          "artifacts": [
            {
              "kind": "model",
              "name": "resnet50",
              "version": "1.4.0"
            }
          ],
          "backend": {
            "engine": "pytorchjob",
            "name": "native"
          },
          "poolName": "gpu-a100",
          "quota": "team-vision",
          "roles": [
            {
              "name": "worker",
              "replicas": 4,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--epochs",
                  "90",
                  "--batch-size",
                  "256"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "NCCL_DEBUG",
                    "value": "INFO"
                  }
                ],
                "image": "registry.axisml.io/training/resnet:1.4.0",
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                }
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "ttlSecondsAfterFinished": 3600
          },
          "unitName": "a100-2x"
        },
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "JobPatchRequest": {
    "description": "更新后的描述。",
    "displayName": "ResNet-50 训练 (v2)"
  },
  "JobSpec": {
    "artifacts": [
      {
        "kind": "model",
        "name": "resnet50",
        "version": "1.4.0"
      }
    ],
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "roles": [
      {
        "name": "worker",
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "template": {
          "args": [
            "--epochs",
            "90",
            "--batch-size",
            "256"
          ],
          "command": [
            "python",
            "train.py"
          ],
          "env": [
            {
              "name": "NCCL_DEBUG",
              "value": "INFO"
            }
          ],
          "image": "registry.axisml.io/training/resnet:1.4.0",
          "resources": {
            "cpu": "8",
            "memory": "64Gi",
            "nvidia.com/gpu": "2"
          }
        }
      }
    ],
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "ttlSecondsAfterFinished": 3600
    },
    "unitName": "a100-2x"
  },
  "LoginRequest": {
    "password": "S3cure-pass",
    "username": "li.wei"
  },
  "LoginResponse": {
    "expiresAt": "2026-06-28T09:25:00Z",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaS53ZWkifQ.sig",
    "tenantRoles": [
      {
        "roleName": "admin",
        "tenantName": "team-vision"
      },
      {
        "roleName": "member",
        "tenantName": "team-nlp"
      }
    ],
    "user": {
      "createdAt": "2026-06-20T08:00:00Z",
      "displayName": "李伟",
      "email": "li.wei@axisml.io",
      "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
      "updatedAt": "2026-06-28T09:30:00Z",
      "username": "li.wei"
    }
  },
  "Member": {
    "addedAt": "2026-06-20T08:00:00Z",
    "displayName": "李伟",
    "email": "li.wei@example.com",
    "roleName": "tenant-admin",
    "userId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "username": "li.wei"
  },
  "MemberCreateRequest": {
    "account": "zhang.san@example.com",
    "roleName": "user"
  },
  "MemberList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "addedAt": "2026-06-20T08:00:00Z",
        "displayName": "李伟",
        "email": "li.wei@example.com",
        "roleName": "tenant-admin",
        "userId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "username": "li.wei"
      }
    ]
  },
  "MemberPatchRequest": {
    "roleName": "tenant-admin"
  },
  "MeResponse": {
    "isSystemAdmin": false,
    "permissions": [
      "job:read",
      "job:write",
      "run:read",
      "run:trigger"
    ],
    "tenantRoles": [
      {
        "roleName": "admin",
        "tenantName": "team-vision"
      },
      {
        "roleName": "member",
        "tenantName": "team-nlp"
      }
    ],
    "user": {
      "createdAt": "2026-06-20T08:00:00Z",
      "displayName": "李伟",
      "email": "li.wei@axisml.io",
      "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
      "updatedAt": "2026-06-28T09:30:00Z",
      "username": "li.wei"
    }
  },
  "MetricPoint": {
    "timestamp": "2026-06-28T09:00:00Z",
    "value": 12.5
  },
  "MetricSeries": {
    "metric": "qps",
    "percentile": "p95",
    "range": "1h",
    "series": [
      {
        "timestamp": "2026-06-28T09:00:00Z",
        "value": 12.5
      },
      {
        "timestamp": "2026-06-28T09:30:00Z",
        "value": 18.3
      },
      {
        "timestamp": "2026-06-28T09:25:00Z",
        "value": 15.1
      }
    ],
    "step": "1m",
    "unit": "req/s"
  },
  "MLRunRole": {
    "name": "worker",
    "replicas": 4,
    "restartPolicy": "OnFailure",
    "template": {
      "args": [
        "--epochs",
        "90",
        "--batch-size",
        "256"
      ],
      "command": [
        "python",
        "train.py"
      ],
      "env": [
        {
          "name": "NCCL_DEBUG",
          "value": "INFO"
        }
      ],
      "image": "registry.axisml.io/training/resnet:1.4.0",
      "resources": {
        "cpu": "8",
        "memory": "64Gi",
        "nvidia.com/gpu": "2"
      }
    }
  },
  "MLRunRoleStatus": {
    "activeReplicas": 4,
    "failedReplicas": 0,
    "name": "worker",
    "readyReplicas": 4,
    "replicas": 4,
    "restartPolicy": "OnFailure",
    "succeededReplicas": 0
  },
  "MLRunSpec": {
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "roles": [
      {
        "name": "worker",
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "template": {
          "args": [
            "--epochs",
            "90",
            "--batch-size",
            "256"
          ],
          "command": [
            "python",
            "train.py"
          ],
          "env": [
            {
              "name": "NCCL_DEBUG",
              "value": "INFO"
            }
          ],
          "image": "registry.axisml.io/training/resnet:1.4.0",
          "resources": {
            "cpu": "8",
            "memory": "64Gi",
            "nvidia.com/gpu": "2"
          }
        }
      }
    ],
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "ttlSecondsAfterFinished": 3600
    }
  },
  "MLService": {
    "accessUrl": "https://gateway.axisml.io/v1/models/llama3-8b",
    "backend": {
      "engine": "llminference",
      "name": "kserve"
    },
    "computeNamespace": "axisml-team-nlp",
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Llama3-8B 在线推理服务。",
    "displayName": "Llama3 对话服务",
    "env": [
      {
        "name": "MAX_TOKENS",
        "value": "4096"
      }
    ],
    "id": "5d2c9b41-3e8f-4a1c-9d7e-6b4f2a1c8e90",
    "image": "registry.axisml.io/serving/vllm:0.6.0",
    "message": "All replicas ready.",
    "modelName": "llama3-8b",
    "modelVersion": "1.2.0",
    "name": "llama3-chat",
    "namespace": "team-nlp",
    "owner": "zhang.san",
    "ownerId": "9f8e7d6c-5b4a-3210-fedc-ba9876543210",
    "phase": "Running",
    "poolName": "gpu-a100",
    "ports": [
      {
        "name": "http",
        "port": 8080
      }
    ],
    "quota": "team-nlp",
    "readyReplicas": 3,
    "replicas": 3,
    "resources": {
      "cpu": "8",
      "memory": "64Gi",
      "nvidia.com/gpu": "1"
    },
    "route": {
      "enabled": true,
      "path": "/v1/models/llama3-8b"
    },
    "tenantName": "team-nlp",
    "unitName": "a100-1x",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "MLServiceCreateRequest": {
    "backend": {
      "engine": "llminference",
      "name": "kserve"
    },
    "description": "Llama3-8B 在线推理服务。",
    "displayName": "Llama3 对话服务",
    "env": [
      {
        "name": "MAX_TOKENS",
        "value": "4096"
      }
    ],
    "image": "registry.axisml.io/serving/vllm:0.6.0",
    "modelName": "llama3-8b",
    "modelVersion": "1.2.0",
    "name": "llama3-chat",
    "poolName": "gpu-a100",
    "ports": [
      {
        "name": "http",
        "port": 8080
      }
    ],
    "quota": "team-nlp",
    "replicas": 3,
    "route": {
      "enabled": true,
      "path": "/v1/models/llama3-8b"
    },
    "unitName": "a100-1x"
  },
  "MLServiceList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "accessUrl": "https://gateway.axisml.io/v1/models/llama3-8b",
        "backend": {
          "engine": "llminference",
          "name": "kserve"
        },
        "computeNamespace": "axisml-team-nlp",
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Llama3-8B 在线推理服务。",
        "displayName": "Llama3 对话服务",
        "env": [
          {
            "name": "MAX_TOKENS",
            "value": "4096"
          }
        ],
        "id": "5d2c9b41-3e8f-4a1c-9d7e-6b4f2a1c8e90",
        "image": "registry.axisml.io/serving/vllm:0.6.0",
        "message": "All replicas ready.",
        "modelName": "llama3-8b",
        "modelVersion": "1.2.0",
        "name": "llama3-chat",
        "namespace": "team-nlp",
        "owner": "zhang.san",
        "ownerId": "9f8e7d6c-5b4a-3210-fedc-ba9876543210",
        "phase": "Running",
        "poolName": "gpu-a100",
        "ports": [
          {
            "name": "http",
            "port": 8080
          }
        ],
        "quota": "team-nlp",
        "readyReplicas": 3,
        "replicas": 3,
        "resources": {
          "cpu": "8",
          "memory": "64Gi",
          "nvidia.com/gpu": "1"
        },
        "route": {
          "enabled": true,
          "path": "/v1/models/llama3-8b"
        },
        "tenantName": "team-nlp",
        "unitName": "a100-1x",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "MLServicePatchRequest": {
    "description": "更新后的描述。",
    "displayName": "Llama3 对话服务 (v2)"
  },
  "MLServiceRoute": {
    "enabled": true,
    "path": "/v1/models/llama3-8b"
  },
  "MLServiceScaleRequest": {
    "replicas": 5
  },
  "Model": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "在 ImageNet 上微调的 ResNet-50 权重。",
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
    "displayName": "ResNet-50 v1.4.0",
    "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
    "name": "resnet50",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "readyAt": "2026-06-28T09:30:00Z",
    "sizeBytes": 102457600,
    "source": "webUpload",
    "status": "Ready",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z",
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0",
    "version": "1.4.0"
  },
  "ModelCompleteRequest": {
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a"
  },
  "ModelInitiateRequest": {
    "description": "在 ImageNet 上微调的 ResNet-50 权重。",
    "displayName": "ResNet-50 v1.4.0",
    "source": "webUpload",
    "version": "1.4.0"
  },
  "ModelInitiateResponse": {
    "expiresAt": "2026-06-28T09:30:00Z",
    "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
    "storageKind": "oci",
    "uploadCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "upload-token"
    },
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0"
  },
  "ModelList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "在 ImageNet 上微调的 ResNet-50 权重。",
        "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
        "displayName": "ResNet-50 v1.4.0",
        "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
        "name": "resnet50",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "readyAt": "2026-06-28T09:30:00Z",
        "sizeBytes": 102457600,
        "source": "webUpload",
        "status": "Ready",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z",
        "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0",
        "version": "1.4.0"
      }
    ],
    "partial": false
  },
  "Pod": {
    "name": "resnet-train-7-worker-0",
    "nodeName": "gpu-node-03",
    "phase": "Running",
    "replicaIndex": 0,
    "restartCount": 0,
    "role": "worker",
    "startedAt": "2026-06-28T09:00:00Z"
  },
  "PodList": {
    "count": 1,
    "items": [
      {
        "name": "resnet-train-7-worker-0",
        "nodeName": "gpu-node-03",
        "phase": "Running",
        "replicaIndex": 0,
        "restartCount": 0,
        "role": "worker",
        "startedAt": "2026-06-28T09:00:00Z"
      }
    ]
  },
  "Problem": {
    "code": "JOB_NOT_FOUND",
    "detail": "Job \"resnet-train\" was not found in tenant \"team-vision\".",
    "instance": "/api/v1/jobs/resnet-train",
    "status": 404,
    "title": "Not Found",
    "type": "https://docs.axisml.io/errors/not-found"
  },
  "ProblemFieldError": {
    "field": "spec.roles",
    "message": "must contain at least one role"
  },
  "Quota": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaCreateRequest": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaList": {
    "count": 1,
    "items": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ],
    "statuses": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x",
            "used": 3
          }
        ]
      }
    ]
  },
  "QuotaPatchRequest": {
    "units": [
      {
        "quantity": 6,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaStatus": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x",
        "used": 3
      }
    ]
  },
  "QuotaUnit": {
    "quantity": 4,
    "unitName": "a100-2x"
  },
  "QuotaUnitStatus": {
    "quantity": 4,
    "unitName": "a100-2x",
    "used": 3
  },
  "RefreshResponse": {
    "expiresAt": "2026-06-28T09:25:00Z",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaS53ZWkifQ.sig2"
  },
  "ResourcePool": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "A100 GPU 资源池。",
    "labels": {
      "tier": "gpu"
    },
    "name": "gpu-a100",
    "nodeCount": 8,
    "nodeSelector": {
      "axisml.io/gpu": "a100"
    },
    "resourceVersion": "184321",
    "units": [
      {
        "description": "2x A100 GPU 计算单元。",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        }
      }
    ],
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "ResourcePoolCreateRequest": {
    "description": "A100 GPU 资源池。",
    "labels": {
      "tier": "gpu"
    },
    "name": "gpu-a100",
    "nodeSelector": {
      "axisml.io/gpu": "a100"
    },
    "units": [
      {
        "description": "2x A100 GPU 计算单元。",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        }
      }
    ]
  },
  "ResourcePoolList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "A100 GPU 资源池。",
        "labels": {
          "tier": "gpu"
        },
        "name": "gpu-a100",
        "nodeCount": 8,
        "nodeSelector": {
          "axisml.io/gpu": "a100"
        },
        "resourceVersion": "184321",
        "units": [
          {
            "description": "2x A100 GPU 计算单元。",
            "limits": {
              "cpu": "16",
              "memory": "128Gi",
              "nvidia.com/gpu": "2"
            },
            "name": "a100-2x",
            "requests": {
              "cpu": "16",
              "memory": "128Gi",
              "nvidia.com/gpu": "2"
            }
          }
        ],
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ]
  },
  "ResourcePoolPatchRequest": {
    "description": "更新后的 A100 GPU 资源池。",
    "nodeSelector": {
      "axisml.io/gpu": "a100",
      "axisml.io/zone": "cn-east-1"
    }
  },
  "ResourceUnit": {
    "description": "2x A100 GPU 计算单元。",
    "limits": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    },
    "name": "a100-2x",
    "requests": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "ResourceUnitCreateRequest": {
    "description": "2x A100 GPU 计算单元。",
    "limits": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    },
    "name": "a100-2x",
    "requests": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "ResourceUnitList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "description": "2x A100 GPU 计算单元。",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        }
      }
    ]
  },
  "ResourceUnitPatchRequest": {
    "description": "更新后的 2x A100 GPU 计算单元。",
    "limits": {
      "cpu": "24",
      "memory": "192Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "RoleTemplate": {
    "args": [
      "--epochs",
      "90",
      "--batch-size",
      "256"
    ],
    "command": [
      "python",
      "train.py"
    ],
    "env": [
      {
        "name": "NCCL_DEBUG",
        "value": "INFO"
      }
    ],
    "image": "registry.axisml.io/training/resnet:1.4.0",
    "resources": {
      "cpu": "8",
      "memory": "64Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "Run": {
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "computeNamespace": "axisml-team-vision",
    "createdAt": "2026-06-28T09:00:00Z",
    "displayName": "ResNet-50 训练 #7",
    "id": "b7d9e3f1-1a2b-3c4d-5e6f-708192a3b4c5",
    "jobName": "resnet-train",
    "message": "All worker replicas ready.",
    "name": "resnet-train-7",
    "namespace": "team-vision",
    "owner": "li.wei",
    "phase": "Running",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "resources": {
      "cpu": "32",
      "memory": "256Gi",
      "nvidia.com/gpu": "8"
    },
    "roles": [
      {
        "activeReplicas": 4,
        "failedReplicas": 0,
        "name": "worker",
        "readyReplicas": 4,
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "succeededReplicas": 0
      }
    ],
    "runNumber": 7,
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "ttlSecondsAfterFinished": 3600
    },
    "spec": {
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      }
    },
    "startedAt": "2026-06-28T09:00:00Z",
    "tenantName": "team-vision",
    "unitName": "a100-2x",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "RunList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "backend": {
          "engine": "pytorchjob",
          "name": "native"
        },
        "computeNamespace": "axisml-team-vision",
        "createdAt": "2026-06-28T09:00:00Z",
        "displayName": "ResNet-50 训练 #7",
        "id": "b7d9e3f1-1a2b-3c4d-5e6f-708192a3b4c5",
        "jobName": "resnet-train",
        "message": "All worker replicas ready.",
        "name": "resnet-train-7",
        "namespace": "team-vision",
        "owner": "li.wei",
        "phase": "Running",
        "poolName": "gpu-a100",
        "quota": "team-vision",
        "resources": {
          "cpu": "32",
          "memory": "256Gi",
          "nvidia.com/gpu": "8"
        },
        "roles": [
          {
            "activeReplicas": 4,
            "failedReplicas": 0,
            "name": "worker",
            "readyReplicas": 4,
            "replicas": 4,
            "restartPolicy": "OnFailure",
            "succeededReplicas": 0
          }
        ],
        "runNumber": 7,
        "runPolicy": {
          "activeDeadlineSeconds": 86400,
          "backoffLimit": 2,
          "ttlSecondsAfterFinished": 3600
        },
        "spec": {
          "backend": {
            "engine": "pytorchjob",
            "name": "native"
          },
          "roles": [
            {
              "name": "worker",
              "replicas": 4,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--epochs",
                  "90",
                  "--batch-size",
                  "256"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "NCCL_DEBUG",
                    "value": "INFO"
                  }
                ],
                "image": "registry.axisml.io/training/resnet:1.4.0",
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                }
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "ttlSecondsAfterFinished": 3600
          }
        },
        "startedAt": "2026-06-28T09:00:00Z",
        "tenantName": "team-vision",
        "unitName": "a100-2x",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "RunPolicy": {
    "activeDeadlineSeconds": 86400,
    "backoffLimit": 2,
    "ttlSecondsAfterFinished": 3600
  },
  "RunTriggerRequest": {
    "displayName": "ResNet-50 训练 #8",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "roles": [
      {
        "args": [
          "--epochs",
          "120"
        ],
        "name": "worker"
      }
    ],
    "unitName": "a100-2x"
  },
  "SecretInit": {
    "name": "wandb-api-key",
    "sourceSecretRef": {
      "name": "wandb-api-key",
      "namespace": "axisml-system"
    },
    "type": "Opaque"
  },
  "SecretSourceRef": {
    "name": "registry-pull",
    "namespace": "axisml-system"
  },
  "ServiceAccountInit": {
    "imagePullSecrets": [
      "registry-pull"
    ],
    "name": "trainer"
  },
  "ServicePort": {
    "name": "http",
    "port": 8080
  },
  "SetPasswordRequest": {
    "currentPassword": "S3cure-pass",
    "newPassword": "S3cure-pass2"
  },
  "Tenant": {
    "activeExperimentRuns": 2,
    "activeJobRuns": 3,
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "计算机视觉模型训练与推理团队。",
    "displayName": "视觉团队",
    "identifier": "team-vision",
    "initResources": {
      "configMaps": [
        {
          "name": "shared-config",
          "sourceConfigMapRef": {
            "name": "shared-config",
            "namespace": "axisml-system"
          }
        }
      ],
      "imagePullSecrets": [
        {
          "name": "registry-pull",
          "sourceSecretRef": {
            "name": "registry-pull",
            "namespace": "axisml-system"
          }
        }
      ],
      "secrets": [
        {
          "name": "wandb-api-key",
          "sourceSecretRef": {
            "name": "wandb-api-key",
            "namespace": "axisml-system"
          },
          "type": "Opaque"
        }
      ],
      "serviceAccounts": [
        {
          "imagePullSecrets": [
            "registry-pull"
          ],
          "name": "trainer"
        }
      ]
    },
    "kubernetesNamespace": "axisml-team-vision",
    "labels": {
      "team": "vision"
    },
    "memberCount": 8,
    "onlineServices": 1,
    "owner": "li.wei",
    "phase": "Active",
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ],
    "status": {
      "conditions": [
        {
          "lastTransitionTime": "2026-06-28T09:30:00Z",
          "message": "Namespace and quota provisioned.",
          "reason": "Provisioned",
          "status": "True",
          "type": "Ready"
        }
      ],
      "message": "Tenant is active.",
      "quotas": [
        {
          "pool": "gpu-a100",
          "units": [
            {
              "quantity": 4,
              "unitName": "a100-2x",
              "used": 3
            }
          ]
        }
      ]
    },
    "suspended": false,
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "TenantCreateRequest": {
    "description": "计算机视觉模型训练与推理团队。",
    "displayName": "视觉团队",
    "identifier": "team-vision",
    "initialAdmin": "li.wei@example.com",
    "kubernetesNamespace": "axisml-team-vision",
    "labels": {
      "team": "vision"
    },
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ]
  },
  "TenantList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "activeExperimentRuns": 2,
        "activeJobRuns": 3,
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "计算机视觉模型训练与推理团队。",
        "displayName": "视觉团队",
        "identifier": "team-vision",
        "initResources": {
          "configMaps": [
            {
              "name": "shared-config",
              "sourceConfigMapRef": {
                "name": "shared-config",
                "namespace": "axisml-system"
              }
            }
          ],
          "imagePullSecrets": [
            {
              "name": "registry-pull",
              "sourceSecretRef": {
                "name": "registry-pull",
                "namespace": "axisml-system"
              }
            }
          ],
          "secrets": [
            {
              "name": "wandb-api-key",
              "sourceSecretRef": {
                "name": "wandb-api-key",
                "namespace": "axisml-system"
              },
              "type": "Opaque"
            }
          ],
          "serviceAccounts": [
            {
              "imagePullSecrets": [
                "registry-pull"
              ],
              "name": "trainer"
            }
          ]
        },
        "kubernetesNamespace": "axisml-team-vision",
        "labels": {
          "team": "vision"
        },
        "memberCount": 8,
        "onlineServices": 1,
        "owner": "li.wei",
        "phase": "Active",
        "quotas": [
          {
            "pool": "gpu-a100",
            "units": [
              {
                "quantity": 4,
                "unitName": "a100-2x"
              }
            ]
          }
        ],
        "status": {
          "conditions": [
            {
              "lastTransitionTime": "2026-06-28T09:30:00Z",
              "message": "Namespace and quota provisioned.",
              "reason": "Provisioned",
              "status": "True",
              "type": "Ready"
            }
          ],
          "message": "Tenant is active.",
          "quotas": [
            {
              "pool": "gpu-a100",
              "units": [
                {
                  "quantity": 4,
                  "unitName": "a100-2x",
                  "used": 3
                }
              ]
            }
          ]
        },
        "suspended": false,
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "TenantPatchRequest": {
    "description": "更新后的团队描述。",
    "displayName": "视觉团队 (核心)"
  },
  "TenantStatus": {
    "conditions": [
      {
        "lastTransitionTime": "2026-06-28T09:30:00Z",
        "message": "Namespace and quota provisioned.",
        "reason": "Provisioned",
        "status": "True",
        "type": "Ready"
      }
    ],
    "message": "Tenant is active.",
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x",
            "used": 3
          }
        ]
      }
    ]
  },
  "TensorBoard": {
    "createdAt": "2026-06-20T08:00:00Z",
    "message": "TensorBoard is serving.",
    "name": "bert-finetune-tb",
    "phase": "Running",
    "url": "https://tb.axisml.io/team-nlp/bert-finetune"
  },
  "TensorBoardRequest": {
    "runs": [
      "bert-finetune-3",
      "bert-finetune-5"
    ]
  },
  "TrafficPolicy": {
    "accessUrl": "https://infer.axisml.io/services/team-vision/resnet-serving/",
    "backends": [
      {
        "actualPct": 90,
        "ready": true,
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 90
      },
      {
        "actualPct": 10,
        "ready": true,
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 10
      }
    ],
    "canaryPercent": 10,
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "ResNet-50 在线推理服务的金丝雀流量切分。",
    "displayName": "ResNet 推理流量",
    "endpoint": {
      "hostname": "infer.axisml.io",
      "path": "/services/team-vision/resnet-serving/"
    },
    "id": "d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f90",
    "message": "Routing 90/10 between stable and canary.",
    "mode": "canary",
    "name": "resnet-serving",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "phase": "Ready",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "TrafficPolicyBackend": {
    "actualPct": 90,
    "ready": true,
    "role": "stable",
    "serviceName": "resnet-serving-v1",
    "weight": 90
  },
  "TrafficPolicyBackendSpec": {
    "role": "canary",
    "serviceName": "resnet-serving-v2",
    "weight": 10
  },
  "TrafficPolicyCreateRequest": {
    "backends": [
      {
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 90
      },
      {
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 10
      }
    ],
    "canaryPercent": 10,
    "description": "ResNet-50 在线推理服务的金丝雀流量切分。",
    "displayName": "ResNet 推理流量",
    "endpoint": {
      "hostname": "infer.axisml.io",
      "path": "/services/team-vision/resnet-serving/"
    },
    "mode": "canary",
    "name": "resnet-serving"
  },
  "TrafficPolicyEndpoint": {
    "hostname": "infer.axisml.io",
    "path": "/services/team-vision/resnet-serving/"
  },
  "TrafficPolicyList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "accessUrl": "https://infer.axisml.io/services/team-vision/resnet-serving/",
        "backends": [
          {
            "actualPct": 90,
            "ready": true,
            "role": "stable",
            "serviceName": "resnet-serving-v1",
            "weight": 90
          },
          {
            "actualPct": 10,
            "ready": true,
            "role": "canary",
            "serviceName": "resnet-serving-v2",
            "weight": 10
          }
        ],
        "canaryPercent": 10,
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "ResNet-50 在线推理服务的金丝雀流量切分。",
        "displayName": "ResNet 推理流量",
        "endpoint": {
          "hostname": "infer.axisml.io",
          "path": "/services/team-vision/resnet-serving/"
        },
        "id": "d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f90",
        "message": "Routing 90/10 between stable and canary.",
        "mode": "canary",
        "name": "resnet-serving",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "phase": "Ready",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "TrafficPolicyPatchRequest": {
    "description": "更新后的描述。",
    "displayName": "ResNet 推理流量 (v2)"
  },
  "TrafficPolicySplitRequest": {
    "backends": [
      {
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 75
      },
      {
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 25
      }
    ],
    "canaryPercent": 25
  },
  "User": {
    "createdAt": "2026-06-20T08:00:00Z",
    "displayName": "李伟",
    "email": "li.wei@axisml.io",
    "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "updatedAt": "2026-06-28T09:30:00Z",
    "username": "li.wei"
  },
  "UserCreateRequest": {
    "displayName": "李伟",
    "email": "li.wei@axisml.io",
    "password": "S3cure-pass",
    "username": "li.wei"
  },
  "UserPatchRequest": {
    "disabled": false,
    "displayName": "李伟 (Vision Lead)",
    "email": "li.wei@axisml.io"
  },
  "UserSummary": {
    "displayName": "李伟",
    "email": "li.wei@axisml.io",
    "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "username": "li.wei"
  },
  "UserSummaryList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "displayName": "李伟",
        "email": "li.wei@axisml.io",
        "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "username": "li.wei"
      }
    ]
  },
  "UserTenantRole": {
    "roleName": "admin",
    "tenantName": "team-vision"
  },
  "Workspace": {
    "computeNamespace": "axisml-team-vision",
    "containerPort": 8888,
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "JupyterLab 交互式开发环境。",
    "desiredState": "Running",
    "displayName": "视觉组开发环境",
    "endpoint": {
      "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
      "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local"
    },
    "id": "f1e2d3c4-5b6a-4798-8c0d-1e2f3a4b5c6d",
    "image": "registry.axisml.io/dev/jupyter:3.0.0",
    "lastStartedAt": "2026-06-28T09:00:00Z",
    "lifecycle": {
      "idleTimeoutSeconds": 3600
    },
    "message": "Workspace is ready.",
    "name": "notebook-dev",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "phase": "Running",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "readyReplicas": 1,
    "replicas": 1,
    "resources": {
      "cpu": "4",
      "memory": "32Gi",
      "nvidia.com/gpu": "1"
    },
    "tenantName": "team-vision",
    "unitName": "a100-1x",
    "updatedAt": "2026-06-28T09:30:00Z",
    "volumes": [
      {
        "mountPath": "/home/jovyan/work",
        "name": "notebook-data",
        "size": "50Gi",
        "storageClass": "standard",
        "used": "12Gi"
      }
    ]
  },
  "WorkspaceCreateRequest": {
    "containerPort": 8888,
    "description": "JupyterLab 交互式开发环境。",
    "displayName": "视觉组开发环境",
    "image": "registry.axisml.io/dev/jupyter:3.0.0",
    "lifecycle": {
      "idleTimeoutSeconds": 3600
    },
    "name": "notebook-dev",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "unitName": "a100-1x",
    "volumes": [
      {
        "mountPath": "/home/jovyan/work",
        "name": "notebook-data",
        "size": "50Gi",
        "storageClass": "standard",
        "used": "12Gi"
      }
    ]
  },
  "WorkspaceDeleteRequest": {
    "deletePvc": false
  },
  "WorkspaceEndpoint": {
    "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
    "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local"
  },
  "WorkspaceLifecycle": {
    "idleTimeoutSeconds": 3600
  },
  "WorkspaceList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "computeNamespace": "axisml-team-vision",
        "containerPort": 8888,
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "JupyterLab 交互式开发环境。",
        "desiredState": "Running",
        "displayName": "视觉组开发环境",
        "endpoint": {
          "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
          "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local"
        },
        "id": "f1e2d3c4-5b6a-4798-8c0d-1e2f3a4b5c6d",
        "image": "registry.axisml.io/dev/jupyter:3.0.0",
        "lastStartedAt": "2026-06-28T09:00:00Z",
        "lifecycle": {
          "idleTimeoutSeconds": 3600
        },
        "message": "Workspace is ready.",
        "name": "notebook-dev",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "phase": "Running",
        "poolName": "gpu-a100",
        "quota": "team-vision",
        "readyReplicas": 1,
        "replicas": 1,
        "resources": {
          "cpu": "4",
          "memory": "32Gi",
          "nvidia.com/gpu": "1"
        },
        "tenantName": "team-vision",
        "unitName": "a100-1x",
        "updatedAt": "2026-06-28T09:30:00Z",
        "volumes": [
          {
            "mountPath": "/home/jovyan/work",
            "name": "notebook-data",
            "size": "50Gi",
            "storageClass": "standard",
            "used": "12Gi"
          }
        ]
      }
    ],
    "partial": false
  },
  "WorkspacePatchRequest": {
    "description": "更新后的描述。",
    "displayName": "视觉组开发环境 (v2)",
    "lifecycle": {
      "idleTimeoutSeconds": 7200
    }
  },
  "WorkspaceVolume": {
    "mountPath": "/home/jovyan/work",
    "name": "notebook-data",
    "size": "50Gi",
    "storageClass": "standard",
    "used": "12Gi"
  },
};

/** Typed accessor: ex<Job>("Job"). Throws if the schema carries no example. */
export function ex<T>(name: string): T {
  const value = examples[name];
  if (value === undefined) {
    throw new Error(`mock example missing for schema "${name}" — run pnpm run gen:mock`);
  }
  return structuredClone(value) as T;
}
