/* eslint-disable */
// AUTO-GENERATED by scripts/gen-mock.mjs from ../../../docs/apis/platform.yaml.
// DO NOT EDIT. Regenerate with: pnpm run gen:mock (or make -C axisml-platform frontend-gen-mock).
//
// Whole-object examples lifted from the OpenAPI spec's component schemas, keyed
// by schema name. These back the in-browser mock (VITE_USE_MOCK_API); the
// authoring lives on the Go DTOs, so fixtures stay in lock-step with the contract.

export const examples: Record<string, unknown> = {
  "ActivityItem": {
    "action": "succeeded",
    "actor": "li.wei",
    "id": "act-9f3a2e5c",
    "kind": "run",
    "name": "resnet-train-7",
    "phase": "Succeeded",
    "timestamp": "2026-06-28T09:25:00Z"
  },
  "ActivityList": {
    "count": 3,
    "items": [
      {
        "action": "succeeded",
        "actor": "li.wei",
        "id": "act-9f3a2e5c",
        "kind": "run",
        "name": "resnet-train-7",
        "phase": "Succeeded",
        "timestamp": "2026-06-28T09:25:00Z"
      },
      {
        "action": "started",
        "actor": "zhang.san",
        "id": "act-7b4f2a1c",
        "kind": "mlservice",
        "name": "llama3-chat",
        "phase": "Ready",
        "timestamp": "2026-06-28T09:30:00Z"
      },
      {
        "action": "created",
        "actor": "li.wei",
        "id": "act-3e8f4a1c",
        "kind": "workspace",
        "name": "notebook-dev",
        "phase": "Running",
        "timestamp": "2026-06-20T08:00:00Z"
      }
    ]
  },
  "ArtifactDefinition": {
    "annotations": {
      "git-commit": "8c1f4e2"
    },
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "ResNet-50 image-classification model.",
    "displayName": "ResNet-50",
    "id": "1f2e3d4c-5b6a-7980-abcd-ef0123456789",
    "kind": "model",
    "labels": {
      "team": "vision"
    },
    "latestVersion": "1.4.0",
    "latestVersionAt": "2026-06-28T09:30:00Z",
    "name": "resnet50",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "spec": {
      "format": "safetensors",
      "framework": "pytorch",
      "parameters": "25.6M",
      "task": "image-classification"
    },
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z",
    "versionCount": 3
  },
  "ArtifactDefinitionCreateRequest": {
    "description": "ResNet-50 image-classification model.",
    "displayName": "ResNet-50",
    "labels": {
      "team": "vision"
    },
    "name": "resnet50"
  },
  "ArtifactDefinitionList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "annotations": {
          "git-commit": "8c1f4e2"
        },
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "ResNet-50 image-classification model.",
        "displayName": "ResNet-50",
        "id": "1f2e3d4c-5b6a-7980-abcd-ef0123456789",
        "kind": "model",
        "labels": {
          "team": "vision"
        },
        "latestVersion": "1.4.0",
        "latestVersionAt": "2026-06-28T09:30:00Z",
        "name": "resnet50",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "spec": {
          "format": "safetensors",
          "framework": "pytorch",
          "parameters": "25.6M",
          "task": "image-classification"
        },
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z",
        "versionCount": 3
      }
    ],
    "partial": false
  },
  "ArtifactDefinitionPatchRequest": {
    "description": "Updated definition description.",
    "displayName": "ResNet-50 (v2)"
  },
  "ArtifactRef": {
    "kind": "model",
    "name": "resnet50",
    "version": "1.4.0"
  },
  "ArtifactResolveResponse": {
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
    "expiresAt": "2026-06-28T09:30:00Z",
    "pullCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "pull-token"
    },
    "storageKind": "oci",
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0"
  },
  "ArtifactUpdateRequest": {
    "description": "Updated version description.",
    "displayName": "ResNet-50 v1.4.0 (calibrated)",
    "labels": {
      "team": "vision"
    }
  },
  "Backend": {
    "engine": "pytorchjob",
    "name": "native"
  },
  "ClusterMeter": {
    "resource": "gpu",
    "total": 48,
    "unit": "cards",
    "used": 36
  },
  "ClusterPoolUsage": {
    "meters": [
      {
        "resource": "gpu",
        "total": 32,
        "unit": "cards",
        "used": 22
      },
      {
        "resource": "cpu",
        "total": 384,
        "unit": "cores",
        "used": 240
      },
      {
        "resource": "memory",
        "total": 2048,
        "unit": "GiB",
        "used": 1228.8
      }
    ],
    "pool": "gpu-a100"
  },
  "ClusterUsage": {
    "pools": [
      {
        "meters": [
          {
            "resource": "gpu",
            "total": 32,
            "unit": "cards",
            "used": 22
          },
          {
            "resource": "cpu",
            "total": 384,
            "unit": "cores",
            "used": 240
          },
          {
            "resource": "memory",
            "total": 2048,
            "unit": "GiB",
            "used": 1228.8
          }
        ],
        "pool": "gpu-a100"
      },
      {
        "meters": [
          {
            "resource": "gpu",
            "total": 16,
            "unit": "cards",
            "used": 14
          },
          {
            "resource": "cpu",
            "total": 256,
            "unit": "cores",
            "used": 180
          },
          {
            "resource": "memory",
            "total": 2048,
            "unit": "GiB",
            "used": 1433.6
          }
        ],
        "pool": "h100-pool"
      },
      {
        "meters": [
          {
            "resource": "gpu",
            "total": 0,
            "unit": "cards",
            "used": 0
          },
          {
            "resource": "cpu",
            "total": 512,
            "unit": "cores",
            "used": 320
          },
          {
            "resource": "memory",
            "total": 1536,
            "unit": "GiB",
            "used": 819.2
          }
        ],
        "pool": "cpu-pool"
      }
    ],
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "Condition": {
    "lastTransitionTime": "2026-06-28T09:30:00Z",
    "message": "All worker replicas are ready.",
    "reason": "AllReplicasReady",
    "status": "True",
    "type": "Ready"
  },
  "ConfigMapInit": {
    "name": "shared-config",
    "sourceConfigMapRef": {
      "name": "shared-config",
      "namespace": "axisml-system"
    }
  },
  "ConfigMapSourceRef": {
    "name": "shared-config",
    "namespace": "axisml-system"
  },
  "DataVolume": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Shared raw datasets directory.",
    "labels": {
      "team": "vision"
    },
    "name": "shared-datasets",
    "size": "2Ti",
    "status": {
      "boundCapacity": "2Ti",
      "mounts": [
        {
          "kind": "Deployment",
          "mountPath": "/data/shared",
          "running": true,
          "workload": "ws-jupyter-3"
        }
      ],
      "phase": "Bound"
    },
    "storageClass": "nfs-rwx"
  },
  "DataVolumeCreateRequest": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "description": "Shared raw datasets directory.",
    "name": "shared-datasets",
    "size": "2Ti",
    "storageClass": "nfs-rwx"
  },
  "DataVolumeList": {
    "count": 1,
    "items": [
      {
        "accessModes": [
          "ReadWriteMany"
        ],
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Shared raw datasets directory.",
        "labels": {
          "team": "vision"
        },
        "name": "shared-datasets",
        "size": "2Ti",
        "status": {
          "boundCapacity": "2Ti",
          "mounts": [
            {
              "kind": "Deployment",
              "mountPath": "/data/shared",
              "running": true,
              "workload": "ws-jupyter-3"
            }
          ],
          "phase": "Bound"
        },
        "storageClass": "nfs-rwx"
      }
    ]
  },
  "DataVolumePatchRequest": {
    "description": "Shared raw datasets directory (expanded).",
    "size": "4Ti"
  },
  "EnvVar": {
    "name": "NCCL_DEBUG",
    "value": "INFO"
  },
  "Event": {
    "count": 1,
    "firstTimestamp": "2026-06-28T09:00:00Z",
    "involvedObject": {
      "kind": "Pod",
      "name": "resnet-train-7-worker-0",
      "namespace": "axisml-team-vision"
    },
    "lastTimestamp": "2026-06-28T09:00:00Z",
    "message": "Successfully assigned resnet-train-7-worker-0 to gpu-node-03.",
    "reason": "Scheduled",
    "source": "default-scheduler",
    "type": "Normal"
  },
  "EventList": {
    "count": 1,
    "items": [
      {
        "count": 1,
        "firstTimestamp": "2026-06-28T09:00:00Z",
        "involvedObject": {
          "kind": "Pod",
          "name": "resnet-train-7-worker-0",
          "namespace": "axisml-team-vision"
        },
        "lastTimestamp": "2026-06-28T09:00:00Z",
        "message": "Successfully assigned resnet-train-7-worker-0 to gpu-node-03.",
        "reason": "Scheduled",
        "source": "default-scheduler",
        "type": "Normal"
      }
    ]
  },
  "Experiment": {
    "annotations": {
      "axisml.io/created-by": "li.wei"
    },
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Training experiment fine-tuning BERT on a Chinese corpus.",
    "displayName": "BERT fine-tuning experiment",
    "id": "d4f8a1b2-3c5e-4a7b-9c0d-1e2f3a4b5c6d",
    "labels": {
      "team": "nlp"
    },
    "name": "bert-finetune",
    "namespace": "team-nlp",
    "owner": "zhang.san",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "runSummary": {
      "active": 1,
      "count": 5,
      "latestPhase": "Succeeded",
      "latestRunAt": "2026-06-28T09:25:00Z",
      "recent": [
        "Succeeded",
        "Running",
        "Succeeded",
        "Failed",
        "Succeeded"
      ]
    },
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "bert-base",
          "version": "2.1.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "kubeflow-trainer"
      },
      "poolName": "gpu-a100",
      "quota": "team-nlp",
      "roles": [
        {
          "name": "worker",
          "replicas": 2,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--lr",
              "0.001",
              "--epochs",
              "10",
              "--batch-size",
              "64"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "WANDB_MODE",
                "value": "offline"
              }
            ],
            "image": "registry.axisml.io/training/bert:2.1.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    },
    "tenantName": "team-nlp",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "ExperimentCreateRequest": {
    "description": "Training experiment fine-tuning BERT on a Chinese corpus.",
    "displayName": "BERT fine-tuning experiment",
    "labels": {
      "team": "nlp"
    },
    "name": "bert-finetune",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "bert-base",
          "version": "2.1.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "kubeflow-trainer"
      },
      "poolName": "gpu-a100",
      "quota": "team-nlp",
      "roles": [
        {
          "name": "worker",
          "replicas": 2,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--lr",
              "0.001",
              "--epochs",
              "10",
              "--batch-size",
              "64"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "WANDB_MODE",
                "value": "offline"
              }
            ],
            "image": "registry.axisml.io/training/bert:2.1.0",
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            }
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    }
  },
  "ExperimentList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "annotations": {
          "axisml.io/created-by": "li.wei"
        },
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Training experiment fine-tuning BERT on a Chinese corpus.",
        "displayName": "BERT fine-tuning experiment",
        "id": "d4f8a1b2-3c5e-4a7b-9c0d-1e2f3a4b5c6d",
        "labels": {
          "team": "nlp"
        },
        "name": "bert-finetune",
        "namespace": "team-nlp",
        "owner": "zhang.san",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "runSummary": {
          "active": 1,
          "count": 5,
          "latestPhase": "Succeeded",
          "latestRunAt": "2026-06-28T09:25:00Z",
          "recent": [
            "Succeeded",
            "Running",
            "Succeeded",
            "Failed",
            "Succeeded"
          ]
        },
        "spec": {
          "artifacts": [
            {
              "kind": "model",
              "name": "bert-base",
              "version": "2.1.0"
            }
          ],
          "backend": {
            "engine": "pytorchjob",
            "name": "kubeflow-trainer"
          },
          "poolName": "gpu-a100",
          "quota": "team-nlp",
          "roles": [
            {
              "name": "worker",
              "replicas": 2,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--lr",
                  "0.001",
                  "--epochs",
                  "10",
                  "--batch-size",
                  "64"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "WANDB_MODE",
                    "value": "offline"
                  }
                ],
                "image": "registry.axisml.io/training/bert:2.1.0",
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                }
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "ttlSecondsAfterFinished": 3600
          },
          "unitName": "a100-2x"
        },
        "tenantName": "team-nlp",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "ExperimentPatchRequest": {
    "description": "Updated description.",
    "displayName": "BERT fine-tuning experiment (v2)"
  },
  "HealthStatus": {
    "components": {
      "artifact-hub": "ok",
      "compute-service": "ok",
      "database": "ok"
    },
    "status": "ok"
  },
  "Image": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Training image with PyTorch 2.3 and CUDA 12.",
    "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b",
    "displayName": "PyTorch Training 2.3.0",
    "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
    "name": "pytorch-train",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "readyAt": "2026-06-28T09:30:00Z",
    "sizeBytes": 5368709120,
    "source": "dockerPush",
    "spec": {
      "baseImage": "nvidia/cuda:12.1.0-runtime",
      "purpose": "training",
      "python": "3.11"
    },
    "status": "Ready",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z",
    "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0",
    "version": "2.3.0"
  },
  "ImageCompleteRequest": {
    "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b"
  },
  "ImageInitiateRequest": {
    "description": "Training image with PyTorch 2.3 and CUDA 12.",
    "displayName": "PyTorch Training 2.3.0",
    "source": "dockerPush",
    "spec": {
      "purpose": "training"
    },
    "version": "2.3.0"
  },
  "ImageInitiateResponse": {
    "expiresAt": "2026-06-28T09:30:00Z",
    "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
    "storageKind": "oci",
    "uploadCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "upload-token"
    },
    "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0"
  },
  "ImageList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Training image with PyTorch 2.3 and CUDA 12.",
        "digest": "sha256:7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b",
        "displayName": "PyTorch Training 2.3.0",
        "id": "a1b2c3d4-5e6f-7081-92a3-b4c5d6e7f809",
        "name": "pytorch-train",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "readyAt": "2026-06-28T09:30:00Z",
        "sizeBytes": 5368709120,
        "source": "dockerPush",
        "spec": {
          "baseImage": "nvidia/cuda:12.1.0-runtime",
          "purpose": "training",
          "python": "3.11"
        },
        "status": "Ready",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z",
        "uri": "oci://registry.axisml.io/team-vision/pytorch-train:2.3.0",
        "version": "2.3.0"
      }
    ],
    "partial": false
  },
  "ImagePullSecretInit": {
    "name": "registry-pull",
    "sourceSecretRef": {
      "name": "registry-pull",
      "namespace": "axisml-system"
    }
  },
  "InitResources": {
    "configMaps": [
      {
        "name": "shared-config",
        "sourceConfigMapRef": {
          "name": "shared-config",
          "namespace": "axisml-system"
        }
      }
    ],
    "imagePullSecrets": [
      {
        "name": "registry-pull",
        "sourceSecretRef": {
          "name": "registry-pull",
          "namespace": "axisml-system"
        }
      }
    ],
    "secrets": [
      {
        "name": "wandb-api-key",
        "sourceSecretRef": {
          "name": "wandb-api-key",
          "namespace": "axisml-system"
        },
        "type": "Opaque"
      }
    ],
    "serviceAccounts": [
      {
        "imagePullSecrets": [
          "registry-pull"
        ],
        "name": "trainer",
        "rbac": {
          "roleRefs": [
            {
              "kind": "ClusterRole",
              "name": "edit"
            }
          ]
        }
      }
    ]
  },
  "Job": {
    "annotations": {
      "axisml.io/created-by": "li.wei",
      "git-commit": "8c1f4e2"
    },
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Distributed ResNet-50 training job on ImageNet.",
    "displayName": "ResNet-50 Training",
    "id": "8c1f4e22-2b7a-4c0e-9b1d-7f3a2e5c9a10",
    "labels": {
      "team": "vision"
    },
    "name": "resnet-train",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "runSummary": {
      "active": 1,
      "count": 7,
      "latestPhase": "Running",
      "latestRunAt": "2026-06-28T09:00:00Z",
      "recent": [
        "Succeeded",
        "Failed",
        "Succeeded",
        "Succeeded",
        "Running"
      ]
    },
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "resnet50",
          "version": "1.4.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "poolName": "gpu-a100",
      "quota": "team-vision",
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "ports": [
              {
                "containerPort": 8080,
                "name": "http",
                "protocol": "TCP"
              }
            ],
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            },
            "volumeMounts": [
              {
                "mountPath": "/data",
                "name": "data"
              }
            ],
            "volumes": [
              {
                "name": "data",
                "persistentVolumeClaim": {
                  "claimName": "resnet-imagenet"
                }
              }
            ]
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "progressDeadlineSeconds": 600,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    },
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "JobCreateRequest": {
    "description": "Distributed ResNet-50 training job on ImageNet.",
    "displayName": "ResNet-50 Training",
    "labels": {
      "team": "vision"
    },
    "name": "resnet-train",
    "spec": {
      "artifacts": [
        {
          "kind": "model",
          "name": "resnet50",
          "version": "1.4.0"
        }
      ],
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "poolName": "gpu-a100",
      "quota": "team-vision",
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "ports": [
              {
                "containerPort": 8080,
                "name": "http",
                "protocol": "TCP"
              }
            ],
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            },
            "volumeMounts": [
              {
                "mountPath": "/data",
                "name": "data"
              }
            ],
            "volumes": [
              {
                "name": "data",
                "persistentVolumeClaim": {
                  "claimName": "resnet-imagenet"
                }
              }
            ]
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "progressDeadlineSeconds": 600,
        "ttlSecondsAfterFinished": 3600
      },
      "unitName": "a100-2x"
    }
  },
  "JobList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "annotations": {
          "axisml.io/created-by": "li.wei",
          "git-commit": "8c1f4e2"
        },
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Distributed ResNet-50 training job on ImageNet.",
        "displayName": "ResNet-50 Training",
        "id": "8c1f4e22-2b7a-4c0e-9b1d-7f3a2e5c9a10",
        "labels": {
          "team": "vision"
        },
        "name": "resnet-train",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "runSummary": {
          "active": 1,
          "count": 7,
          "latestPhase": "Running",
          "latestRunAt": "2026-06-28T09:00:00Z",
          "recent": [
            "Succeeded",
            "Failed",
            "Succeeded",
            "Succeeded",
            "Running"
          ]
        },
        "spec": {
          "artifacts": [
            {
              "kind": "model",
              "name": "resnet50",
              "version": "1.4.0"
            }
          ],
          "backend": {
            "engine": "pytorchjob",
            "name": "native"
          },
          "poolName": "gpu-a100",
          "quota": "team-vision",
          "roles": [
            {
              "name": "worker",
              "replicas": 4,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--epochs",
                  "90",
                  "--batch-size",
                  "256"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "NCCL_DEBUG",
                    "value": "INFO"
                  }
                ],
                "image": "registry.axisml.io/training/resnet:1.4.0",
                "ports": [
                  {
                    "containerPort": 8080,
                    "name": "http",
                    "protocol": "TCP"
                  }
                ],
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                },
                "volumeMounts": [
                  {
                    "mountPath": "/data",
                    "name": "data"
                  }
                ],
                "volumes": [
                  {
                    "name": "data",
                    "persistentVolumeClaim": {
                      "claimName": "resnet-imagenet"
                    }
                  }
                ]
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "progressDeadlineSeconds": 600,
            "ttlSecondsAfterFinished": 3600
          },
          "unitName": "a100-2x"
        },
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "JobPatchRequest": {
    "description": "Updated description.",
    "displayName": "ResNet-50 Training (v2)"
  },
  "JobSpec": {
    "artifacts": [
      {
        "kind": "model",
        "name": "resnet50",
        "version": "1.4.0"
      }
    ],
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "roles": [
      {
        "name": "worker",
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "template": {
          "args": [
            "--epochs",
            "90",
            "--batch-size",
            "256"
          ],
          "command": [
            "python",
            "train.py"
          ],
          "env": [
            {
              "name": "NCCL_DEBUG",
              "value": "INFO"
            }
          ],
          "image": "registry.axisml.io/training/resnet:1.4.0",
          "ports": [
            {
              "containerPort": 8080,
              "name": "http",
              "protocol": "TCP"
            }
          ],
          "resources": {
            "cpu": "8",
            "memory": "64Gi",
            "nvidia.com/gpu": "2"
          },
          "volumeMounts": [
            {
              "mountPath": "/data",
              "name": "data"
            }
          ],
          "volumes": [
            {
              "name": "data",
              "persistentVolumeClaim": {
                "claimName": "resnet-imagenet"
              }
            }
          ]
        }
      }
    ],
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "progressDeadlineSeconds": 600,
      "ttlSecondsAfterFinished": 3600
    },
    "unitName": "a100-2x"
  },
  "LoginRequest": {
    "password": "S3cure-pass",
    "username": "li.wei"
  },
  "LoginResponse": {
    "expiresAt": "2026-06-28T09:25:00Z",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaS53ZWkifQ.sig",
    "tenantRoles": [
      {
        "roleName": "admin",
        "tenantName": "team-vision"
      },
      {
        "roleName": "member",
        "tenantName": "team-nlp"
      }
    ],
    "user": {
      "createdAt": "2026-06-20T08:00:00Z",
      "disabled": false,
      "displayName": "Li Wei",
      "email": "li.wei@axisml.io",
      "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
      "mustChangePassword": false,
      "updatedAt": "2026-06-28T09:30:00Z",
      "username": "li.wei"
    }
  },
  "Member": {
    "addedAt": "2026-06-20T08:00:00Z",
    "displayName": "Li Wei",
    "email": "li.wei@example.com",
    "roleName": "tenant-admin",
    "userId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "username": "li.wei"
  },
  "MemberCreateRequest": {
    "account": "zhang.san@example.com",
    "roleName": "user"
  },
  "MemberList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "addedAt": "2026-06-20T08:00:00Z",
        "displayName": "Li Wei",
        "email": "li.wei@example.com",
        "roleName": "tenant-admin",
        "userId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "username": "li.wei"
      }
    ]
  },
  "MemberPatchRequest": {
    "roleName": "tenant-admin"
  },
  "MeResponse": {
    "isSystemAdmin": false,
    "permissions": [
      "job:read",
      "job:write",
      "run:read",
      "run:trigger"
    ],
    "tenantRoles": [
      {
        "roleName": "admin",
        "tenantName": "team-vision"
      },
      {
        "roleName": "member",
        "tenantName": "team-nlp"
      }
    ],
    "user": {
      "createdAt": "2026-06-20T08:00:00Z",
      "disabled": false,
      "displayName": "Li Wei",
      "email": "li.wei@axisml.io",
      "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
      "mustChangePassword": false,
      "updatedAt": "2026-06-28T09:30:00Z",
      "username": "li.wei"
    }
  },
  "MetricPoint": {
    "timestamp": "2026-06-28T09:00:00Z",
    "value": 12.5
  },
  "MetricSeries": {
    "metric": "qps",
    "percentile": "p95",
    "range": "1h",
    "series": [
      {
        "timestamp": "2026-06-28T09:00:00Z",
        "value": 12.5
      },
      {
        "timestamp": "2026-06-28T09:30:00Z",
        "value": 18.3
      },
      {
        "timestamp": "2026-06-28T09:25:00Z",
        "value": 15.1
      }
    ],
    "step": "1m",
    "unit": "req/s"
  },
  "MLRunRole": {
    "name": "worker",
    "replicas": 4,
    "restartPolicy": "OnFailure",
    "template": {
      "args": [
        "--epochs",
        "90",
        "--batch-size",
        "256"
      ],
      "command": [
        "python",
        "train.py"
      ],
      "env": [
        {
          "name": "NCCL_DEBUG",
          "value": "INFO"
        }
      ],
      "image": "registry.axisml.io/training/resnet:1.4.0",
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "resources": {
        "cpu": "8",
        "memory": "64Gi",
        "nvidia.com/gpu": "2"
      },
      "volumeMounts": [
        {
          "mountPath": "/data",
          "name": "data"
        }
      ],
      "volumes": [
        {
          "name": "data",
          "persistentVolumeClaim": {
            "claimName": "resnet-imagenet"
          }
        }
      ]
    }
  },
  "MLRunRoleStatus": {
    "activeReplicas": 4,
    "failedReplicas": 0,
    "name": "worker",
    "readyReplicas": 4,
    "replicas": 4,
    "restartPolicy": "OnFailure",
    "succeededReplicas": 0,
    "template": {
      "args": [
        "--epochs",
        "90",
        "--batch-size",
        "256"
      ],
      "command": [
        "python",
        "train.py"
      ],
      "env": [
        {
          "name": "NCCL_DEBUG",
          "value": "INFO"
        }
      ],
      "image": "registry.axisml.io/training/resnet:1.4.0",
      "ports": [
        {
          "containerPort": 8080,
          "name": "http",
          "protocol": "TCP"
        }
      ],
      "resources": {
        "cpu": "8",
        "memory": "64Gi",
        "nvidia.com/gpu": "2"
      },
      "volumeMounts": [
        {
          "mountPath": "/data",
          "name": "data"
        }
      ],
      "volumes": [
        {
          "name": "data",
          "persistentVolumeClaim": {
            "claimName": "resnet-imagenet"
          }
        }
      ]
    }
  },
  "MLRunSpec": {
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "roles": [
      {
        "name": "worker",
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "template": {
          "args": [
            "--epochs",
            "90",
            "--batch-size",
            "256"
          ],
          "command": [
            "python",
            "train.py"
          ],
          "env": [
            {
              "name": "NCCL_DEBUG",
              "value": "INFO"
            }
          ],
          "image": "registry.axisml.io/training/resnet:1.4.0",
          "ports": [
            {
              "containerPort": 8080,
              "name": "http",
              "protocol": "TCP"
            }
          ],
          "resources": {
            "cpu": "8",
            "memory": "64Gi",
            "nvidia.com/gpu": "2"
          },
          "volumeMounts": [
            {
              "mountPath": "/data",
              "name": "data"
            }
          ],
          "volumes": [
            {
              "name": "data",
              "persistentVolumeClaim": {
                "claimName": "resnet-imagenet"
              }
            }
          ]
        }
      }
    ],
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "progressDeadlineSeconds": 600,
      "ttlSecondsAfterFinished": 3600
    },
    "scheduling": {
      "minMember": 4,
      "priorityClass": "high-priority",
      "quota": "axisml-team-vision-gpu-a100-default"
    }
  },
  "MLService": {
    "accessUrl": "https://gateway.axisml.io/v1/models/llama3-8b",
    "args": [
      "--model",
      "meta-llama/Llama-3-8b",
      "--max-model-len",
      "8192"
    ],
    "backend": {
      "engine": "llminference",
      "name": "kserve"
    },
    "command": [
      "python",
      "-m",
      "vllm.entrypoints.openai.api_server"
    ],
    "computeNamespace": "axisml-team-nlp",
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Llama3-8B online inference service.",
    "desiredState": "Running",
    "displayName": "Llama3 chat service",
    "env": [
      {
        "name": "MAX_TOKENS",
        "value": "4096"
      }
    ],
    "id": "5d2c9b41-3e8f-4a1c-9d7e-6b4f2a1c8e90",
    "image": "registry.axisml.io/serving/vllm:0.6.0",
    "message": "All replicas ready.",
    "modelName": "llama3-8b",
    "modelVersion": "1.2.0",
    "name": "llama3-chat",
    "namespace": "team-nlp",
    "owner": "zhang.san",
    "ownerId": "9f8e7d6c-5b4a-3210-fedc-ba9876543210",
    "phase": "Ready",
    "poolName": "gpu-a100",
    "ports": [
      {
        "name": "http",
        "port": 8080
      }
    ],
    "quota": "team-nlp",
    "readyReplicas": 3,
    "replicas": 3,
    "resources": {
      "cpu": "8",
      "memory": "64Gi",
      "nvidia.com/gpu": "1"
    },
    "route": {
      "enabled": true,
      "path": "/v1/models/llama3-8b"
    },
    "tenantDisplayName": "Vision Team",
    "tenantName": "team-nlp",
    "unitName": "a100-1x",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "MLServiceCreateRequest": {
    "backend": {
      "engine": "llminference",
      "name": "kserve"
    },
    "description": "Llama3-8B online inference service.",
    "displayName": "Llama3 chat service",
    "env": [
      {
        "name": "MAX_TOKENS",
        "value": "4096"
      }
    ],
    "image": "registry.axisml.io/serving/vllm:0.6.0",
    "modelName": "llama3-8b",
    "modelVersion": "1.2.0",
    "name": "llama3-chat",
    "poolName": "gpu-a100",
    "ports": [
      {
        "name": "http",
        "port": 8080
      }
    ],
    "quota": "team-nlp",
    "replicas": 3,
    "route": {
      "enabled": true,
      "path": "/v1/models/llama3-8b"
    },
    "unitName": "a100-1x"
  },
  "MLServiceList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "accessUrl": "https://gateway.axisml.io/v1/models/llama3-8b",
        "args": [
          "--model",
          "meta-llama/Llama-3-8b",
          "--max-model-len",
          "8192"
        ],
        "backend": {
          "engine": "llminference",
          "name": "kserve"
        },
        "command": [
          "python",
          "-m",
          "vllm.entrypoints.openai.api_server"
        ],
        "computeNamespace": "axisml-team-nlp",
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Llama3-8B online inference service.",
        "desiredState": "Running",
        "displayName": "Llama3 chat service",
        "env": [
          {
            "name": "MAX_TOKENS",
            "value": "4096"
          }
        ],
        "id": "5d2c9b41-3e8f-4a1c-9d7e-6b4f2a1c8e90",
        "image": "registry.axisml.io/serving/vllm:0.6.0",
        "message": "All replicas ready.",
        "modelName": "llama3-8b",
        "modelVersion": "1.2.0",
        "name": "llama3-chat",
        "namespace": "team-nlp",
        "owner": "zhang.san",
        "ownerId": "9f8e7d6c-5b4a-3210-fedc-ba9876543210",
        "phase": "Ready",
        "poolName": "gpu-a100",
        "ports": [
          {
            "name": "http",
            "port": 8080
          }
        ],
        "quota": "team-nlp",
        "readyReplicas": 3,
        "replicas": 3,
        "resources": {
          "cpu": "8",
          "memory": "64Gi",
          "nvidia.com/gpu": "1"
        },
        "route": {
          "enabled": true,
          "path": "/v1/models/llama3-8b"
        },
        "tenantDisplayName": "Vision Team",
        "tenantName": "team-nlp",
        "unitName": "a100-1x",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "MLServicePatchRequest": {
    "description": "Updated description.",
    "displayName": "Llama3 chat service (v2)"
  },
  "MLServiceRoute": {
    "enabled": true,
    "path": "/v1/models/llama3-8b"
  },
  "MLServiceScaleRequest": {
    "replicas": 5
  },
  "Model": {
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "ResNet-50 weights fine-tuned on ImageNet.",
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
    "displayName": "ResNet-50 v1.4.0",
    "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
    "name": "resnet50",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "readyAt": "2026-06-28T09:30:00Z",
    "sizeBytes": 102457600,
    "source": "webUpload",
    "spec": {
      "format": "safetensors",
      "framework": "pytorch",
      "parameters": "25.6M",
      "task": "image-classification"
    },
    "status": "Ready",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z",
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0",
    "version": "1.4.0"
  },
  "ModelCompleteRequest": {
    "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a"
  },
  "ModelInitiateRequest": {
    "description": "ResNet-50 weights fine-tuned on ImageNet.",
    "displayName": "ResNet-50 v1.4.0",
    "source": "webUpload",
    "version": "1.4.0"
  },
  "ModelInitiateResponse": {
    "expiresAt": "2026-06-28T09:30:00Z",
    "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
    "storageKind": "oci",
    "uploadCredentials": {
      "password": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
      "username": "upload-token"
    },
    "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0"
  },
  "ModelList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "ResNet-50 weights fine-tuned on ImageNet.",
        "digest": "sha256:9b0d5a2c7f3148e1f4a6c8e3d2b4a6c8e1f9b0d5a2c7f3148e1f4a6c8e3d2b4a",
        "displayName": "ResNet-50 v1.4.0",
        "id": "c4a7f1e9-3d2b-4a6c-8e1f-9b0d5a2c7f31",
        "name": "resnet50",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "readyAt": "2026-06-28T09:30:00Z",
        "sizeBytes": 102457600,
        "source": "webUpload",
        "spec": {
          "format": "safetensors",
          "framework": "pytorch",
          "parameters": "25.6M",
          "task": "image-classification"
        },
        "status": "Ready",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z",
        "uri": "oci://registry.axisml.io/team-vision/resnet50:1.4.0",
        "version": "1.4.0"
      }
    ],
    "partial": false
  },
  "Pod": {
    "name": "resnet-train-7-worker-0",
    "nodeName": "gpu-node-03",
    "phase": "Running",
    "replicaIndex": 0,
    "restartCount": 0,
    "role": "worker",
    "startedAt": "2026-06-28T09:00:00Z"
  },
  "PodList": {
    "count": 1,
    "items": [
      {
        "name": "resnet-train-7-worker-0",
        "nodeName": "gpu-node-03",
        "phase": "Running",
        "replicaIndex": 0,
        "restartCount": 0,
        "role": "worker",
        "startedAt": "2026-06-28T09:00:00Z"
      }
    ]
  },
  "Problem": {
    "code": "JOB_NOT_FOUND",
    "detail": "Job \"resnet-train\" was not found in tenant \"team-vision\".",
    "instance": "/api/v1/jobs/resnet-train",
    "status": 404,
    "title": "Not Found",
    "type": "https://docs.axisml.io/errors/not-found"
  },
  "ProblemFieldError": {
    "field": "spec.roles",
    "message": "must contain at least one role"
  },
  "Quota": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaCreateRequest": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaList": {
    "count": 1,
    "items": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ],
    "statuses": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x",
            "used": 3
          }
        ]
      }
    ]
  },
  "QuotaPatchRequest": {
    "units": [
      {
        "quantity": 6,
        "unitName": "a100-2x"
      }
    ]
  },
  "QuotaStatus": {
    "pool": "gpu-a100",
    "units": [
      {
        "quantity": 4,
        "unitName": "a100-2x",
        "used": 3
      }
    ]
  },
  "QuotaUnit": {
    "quantity": 4,
    "unitName": "a100-2x"
  },
  "QuotaUnitStatus": {
    "quantity": 4,
    "unitName": "a100-2x",
    "used": 3
  },
  "RefreshResponse": {
    "expiresAt": "2026-06-28T09:25:00Z",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsaS53ZWkifQ.sig2"
  },
  "ResourcePool": {
    "annotations": {
      "axisml.io/cost-center": "ml-platform",
      "axisml.io/created-by": "admin"
    },
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "A100 GPU resource pool.",
    "labels": {
      "tier": "gpu"
    },
    "name": "gpu-a100",
    "nodeCount": 8,
    "nodeSelector": {
      "axisml.io/gpu": "a100"
    },
    "resourceVersion": "184321",
    "tolerations": [
      {
        "effect": "NoSchedule",
        "key": "nvidia.com/gpu",
        "operator": "Exists"
      }
    ],
    "units": [
      {
        "annotations": {
          "axisml.io/cost-center": "ml-platform",
          "axisml.io/created-by": "admin"
        },
        "description": "2x A100 GPU compute unit.",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "nodeSelector": {
          "arch": "amd64",
          "gpu.product": "A100"
        },
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "nvidia.com/gpu",
            "operator": "Exists"
          }
        ]
      }
    ],
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "ResourcePoolCreateRequest": {
    "description": "A100 GPU resource pool.",
    "labels": {
      "tier": "gpu"
    },
    "name": "gpu-a100",
    "nodeSelector": {
      "axisml.io/gpu": "a100"
    },
    "units": [
      {
        "description": "2x A100 GPU compute unit.",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        }
      }
    ]
  },
  "ResourcePoolList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "annotations": {
          "axisml.io/cost-center": "ml-platform",
          "axisml.io/created-by": "admin"
        },
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "A100 GPU resource pool.",
        "labels": {
          "tier": "gpu"
        },
        "name": "gpu-a100",
        "nodeCount": 8,
        "nodeSelector": {
          "axisml.io/gpu": "a100"
        },
        "resourceVersion": "184321",
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "nvidia.com/gpu",
            "operator": "Exists"
          }
        ],
        "units": [
          {
            "annotations": {
              "axisml.io/cost-center": "ml-platform",
              "axisml.io/created-by": "admin"
            },
            "description": "2x A100 GPU compute unit.",
            "limits": {
              "cpu": "16",
              "memory": "128Gi",
              "nvidia.com/gpu": "2"
            },
            "name": "a100-2x",
            "nodeSelector": {
              "arch": "amd64",
              "gpu.product": "A100"
            },
            "requests": {
              "cpu": "16",
              "memory": "128Gi",
              "nvidia.com/gpu": "2"
            },
            "tolerations": [
              {
                "effect": "NoSchedule",
                "key": "nvidia.com/gpu",
                "operator": "Exists"
              }
            ]
          }
        ],
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ]
  },
  "ResourcePoolPatchRequest": {
    "description": "Updated A100 GPU resource pool.",
    "nodeSelector": {
      "axisml.io/gpu": "a100",
      "axisml.io/zone": "cn-east-1"
    }
  },
  "ResourceUnit": {
    "annotations": {
      "axisml.io/cost-center": "ml-platform",
      "axisml.io/created-by": "admin"
    },
    "description": "2x A100 GPU compute unit.",
    "limits": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    },
    "name": "a100-2x",
    "nodeSelector": {
      "arch": "amd64",
      "gpu.product": "A100"
    },
    "requests": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    },
    "tolerations": [
      {
        "effect": "NoSchedule",
        "key": "nvidia.com/gpu",
        "operator": "Exists"
      }
    ]
  },
  "ResourceUnitCreateRequest": {
    "description": "2x A100 GPU compute unit.",
    "limits": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    },
    "name": "a100-2x",
    "requests": {
      "cpu": "16",
      "memory": "128Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "ResourceUnitList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "annotations": {
          "axisml.io/cost-center": "ml-platform",
          "axisml.io/created-by": "admin"
        },
        "description": "2x A100 GPU compute unit.",
        "limits": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "name": "a100-2x",
        "nodeSelector": {
          "arch": "amd64",
          "gpu.product": "A100"
        },
        "requests": {
          "cpu": "16",
          "memory": "128Gi",
          "nvidia.com/gpu": "2"
        },
        "tolerations": [
          {
            "effect": "NoSchedule",
            "key": "nvidia.com/gpu",
            "operator": "Exists"
          }
        ]
      }
    ]
  },
  "ResourceUnitPatchRequest": {
    "description": "Updated 2x A100 GPU compute unit.",
    "limits": {
      "cpu": "24",
      "memory": "192Gi",
      "nvidia.com/gpu": "2"
    }
  },
  "RoleTemplate": {
    "args": [
      "--epochs",
      "90",
      "--batch-size",
      "256"
    ],
    "command": [
      "python",
      "train.py"
    ],
    "env": [
      {
        "name": "NCCL_DEBUG",
        "value": "INFO"
      }
    ],
    "image": "registry.axisml.io/training/resnet:1.4.0",
    "ports": [
      {
        "containerPort": 8080,
        "name": "http",
        "protocol": "TCP"
      }
    ],
    "resources": {
      "cpu": "8",
      "memory": "64Gi",
      "nvidia.com/gpu": "2"
    },
    "volumeMounts": [
      {
        "mountPath": "/data",
        "name": "data"
      }
    ],
    "volumes": [
      {
        "name": "data",
        "persistentVolumeClaim": {
          "claimName": "resnet-imagenet"
        }
      }
    ]
  },
  "Run": {
    "backend": {
      "engine": "pytorchjob",
      "name": "native"
    },
    "computeNamespace": "axisml-team-vision",
    "createdAt": "2026-06-28T09:00:00Z",
    "description": "Distributed ResNet-50 training run on ImageNet.",
    "displayName": "ResNet-50 Training #7",
    "id": "b7d9e3f1-1a2b-3c4d-5e6f-708192a3b4c5",
    "jobName": "resnet-train",
    "message": "All worker replicas ready.",
    "name": "resnet-train-7",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "phase": "Running",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "resources": {
      "cpu": "32",
      "memory": "256Gi",
      "nvidia.com/gpu": "8"
    },
    "roles": [
      {
        "activeReplicas": 4,
        "failedReplicas": 0,
        "name": "worker",
        "readyReplicas": 4,
        "replicas": 4,
        "restartPolicy": "OnFailure",
        "succeededReplicas": 0,
        "template": {
          "args": [
            "--epochs",
            "90",
            "--batch-size",
            "256"
          ],
          "command": [
            "python",
            "train.py"
          ],
          "env": [
            {
              "name": "NCCL_DEBUG",
              "value": "INFO"
            }
          ],
          "image": "registry.axisml.io/training/resnet:1.4.0",
          "ports": [
            {
              "containerPort": 8080,
              "name": "http",
              "protocol": "TCP"
            }
          ],
          "resources": {
            "cpu": "8",
            "memory": "64Gi",
            "nvidia.com/gpu": "2"
          },
          "volumeMounts": [
            {
              "mountPath": "/data",
              "name": "data"
            }
          ],
          "volumes": [
            {
              "name": "data",
              "persistentVolumeClaim": {
                "claimName": "resnet-imagenet"
              }
            }
          ]
        }
      }
    ],
    "runNumber": 7,
    "runPolicy": {
      "activeDeadlineSeconds": 86400,
      "backoffLimit": 2,
      "progressDeadlineSeconds": 600,
      "ttlSecondsAfterFinished": 3600
    },
    "scheduledAt": "2026-06-28T09:00:00Z",
    "spec": {
      "backend": {
        "engine": "pytorchjob",
        "name": "native"
      },
      "roles": [
        {
          "name": "worker",
          "replicas": 4,
          "restartPolicy": "OnFailure",
          "template": {
            "args": [
              "--epochs",
              "90",
              "--batch-size",
              "256"
            ],
            "command": [
              "python",
              "train.py"
            ],
            "env": [
              {
                "name": "NCCL_DEBUG",
                "value": "INFO"
              }
            ],
            "image": "registry.axisml.io/training/resnet:1.4.0",
            "ports": [
              {
                "containerPort": 8080,
                "name": "http",
                "protocol": "TCP"
              }
            ],
            "resources": {
              "cpu": "8",
              "memory": "64Gi",
              "nvidia.com/gpu": "2"
            },
            "volumeMounts": [
              {
                "mountPath": "/data",
                "name": "data"
              }
            ],
            "volumes": [
              {
                "name": "data",
                "persistentVolumeClaim": {
                  "claimName": "resnet-imagenet"
                }
              }
            ]
          }
        }
      ],
      "runPolicy": {
        "activeDeadlineSeconds": 86400,
        "backoffLimit": 2,
        "progressDeadlineSeconds": 600,
        "ttlSecondsAfterFinished": 3600
      },
      "scheduling": {
        "minMember": 4,
        "priorityClass": "high-priority",
        "quota": "axisml-team-vision-gpu-a100-default"
      }
    },
    "startedAt": "2026-06-28T09:00:00Z",
    "tenantDisplayName": "Vision Team",
    "tenantName": "team-vision",
    "unitName": "a100-2x",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "RunList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "backend": {
          "engine": "pytorchjob",
          "name": "native"
        },
        "computeNamespace": "axisml-team-vision",
        "createdAt": "2026-06-28T09:00:00Z",
        "description": "Distributed ResNet-50 training run on ImageNet.",
        "displayName": "ResNet-50 Training #7",
        "id": "b7d9e3f1-1a2b-3c4d-5e6f-708192a3b4c5",
        "jobName": "resnet-train",
        "message": "All worker replicas ready.",
        "name": "resnet-train-7",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "phase": "Running",
        "poolName": "gpu-a100",
        "quota": "team-vision",
        "resources": {
          "cpu": "32",
          "memory": "256Gi",
          "nvidia.com/gpu": "8"
        },
        "roles": [
          {
            "activeReplicas": 4,
            "failedReplicas": 0,
            "name": "worker",
            "readyReplicas": 4,
            "replicas": 4,
            "restartPolicy": "OnFailure",
            "succeededReplicas": 0,
            "template": {
              "args": [
                "--epochs",
                "90",
                "--batch-size",
                "256"
              ],
              "command": [
                "python",
                "train.py"
              ],
              "env": [
                {
                  "name": "NCCL_DEBUG",
                  "value": "INFO"
                }
              ],
              "image": "registry.axisml.io/training/resnet:1.4.0",
              "ports": [
                {
                  "containerPort": 8080,
                  "name": "http",
                  "protocol": "TCP"
                }
              ],
              "resources": {
                "cpu": "8",
                "memory": "64Gi",
                "nvidia.com/gpu": "2"
              },
              "volumeMounts": [
                {
                  "mountPath": "/data",
                  "name": "data"
                }
              ],
              "volumes": [
                {
                  "name": "data",
                  "persistentVolumeClaim": {
                    "claimName": "resnet-imagenet"
                  }
                }
              ]
            }
          }
        ],
        "runNumber": 7,
        "runPolicy": {
          "activeDeadlineSeconds": 86400,
          "backoffLimit": 2,
          "progressDeadlineSeconds": 600,
          "ttlSecondsAfterFinished": 3600
        },
        "scheduledAt": "2026-06-28T09:00:00Z",
        "spec": {
          "backend": {
            "engine": "pytorchjob",
            "name": "native"
          },
          "roles": [
            {
              "name": "worker",
              "replicas": 4,
              "restartPolicy": "OnFailure",
              "template": {
                "args": [
                  "--epochs",
                  "90",
                  "--batch-size",
                  "256"
                ],
                "command": [
                  "python",
                  "train.py"
                ],
                "env": [
                  {
                    "name": "NCCL_DEBUG",
                    "value": "INFO"
                  }
                ],
                "image": "registry.axisml.io/training/resnet:1.4.0",
                "ports": [
                  {
                    "containerPort": 8080,
                    "name": "http",
                    "protocol": "TCP"
                  }
                ],
                "resources": {
                  "cpu": "8",
                  "memory": "64Gi",
                  "nvidia.com/gpu": "2"
                },
                "volumeMounts": [
                  {
                    "mountPath": "/data",
                    "name": "data"
                  }
                ],
                "volumes": [
                  {
                    "name": "data",
                    "persistentVolumeClaim": {
                      "claimName": "resnet-imagenet"
                    }
                  }
                ]
              }
            }
          ],
          "runPolicy": {
            "activeDeadlineSeconds": 86400,
            "backoffLimit": 2,
            "progressDeadlineSeconds": 600,
            "ttlSecondsAfterFinished": 3600
          },
          "scheduling": {
            "minMember": 4,
            "priorityClass": "high-priority",
            "quota": "axisml-team-vision-gpu-a100-default"
          }
        },
        "startedAt": "2026-06-28T09:00:00Z",
        "tenantDisplayName": "Vision Team",
        "tenantName": "team-vision",
        "unitName": "a100-2x",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "RunPolicy": {
    "activeDeadlineSeconds": 86400,
    "backoffLimit": 2,
    "progressDeadlineSeconds": 600,
    "ttlSecondsAfterFinished": 3600
  },
  "RunSummary": {
    "active": 1,
    "count": 7,
    "latestPhase": "Running",
    "latestRunAt": "2026-06-28T09:00:00Z",
    "recent": [
      "Succeeded",
      "Failed",
      "Succeeded",
      "Succeeded",
      "Running"
    ]
  },
  "RunTriggerRequest": {
    "displayName": "ResNet-50 Training #8",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "roles": [
      {
        "args": [
          "--epochs",
          "120"
        ],
        "name": "worker"
      }
    ],
    "unitName": "a100-2x"
  },
  "SecretInit": {
    "name": "wandb-api-key",
    "sourceSecretRef": {
      "name": "wandb-api-key",
      "namespace": "axisml-system"
    },
    "type": "Opaque"
  },
  "SecretSourceRef": {
    "name": "registry-pull",
    "namespace": "axisml-system"
  },
  "ServiceAccountInit": {
    "imagePullSecrets": [
      "registry-pull"
    ],
    "name": "trainer",
    "rbac": {
      "roleRefs": [
        {
          "kind": "ClusterRole",
          "name": "edit"
        }
      ]
    }
  },
  "ServicePort": {
    "name": "http",
    "port": 8080
  },
  "SetPasswordRequest": {
    "currentPassword": "S3cure-pass",
    "newPassword": "S3cure-pass2"
  },
  "StorageClass": {
    "allowVolumeExpansion": true,
    "default": false,
    "name": "nfs-rwx",
    "provisioner": "nfs.csi.k8s.io"
  },
  "StorageClassList": {
    "count": 1,
    "items": [
      {
        "allowVolumeExpansion": true,
        "default": false,
        "name": "nfs-rwx",
        "provisioner": "nfs.csi.k8s.io"
      }
    ]
  },
  "Tenant": {
    "activeExperimentRuns": 2,
    "activeJobRuns": 3,
    "annotations": {
      "axisml.io/created-by": "system-admin"
    },
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Computer-vision model training and inference team.",
    "displayName": "Vision Team",
    "identifier": "team-vision",
    "initResources": {
      "configMaps": [
        {
          "name": "shared-config",
          "sourceConfigMapRef": {
            "name": "shared-config",
            "namespace": "axisml-system"
          }
        }
      ],
      "imagePullSecrets": [
        {
          "name": "registry-pull",
          "sourceSecretRef": {
            "name": "registry-pull",
            "namespace": "axisml-system"
          }
        }
      ],
      "secrets": [
        {
          "name": "wandb-api-key",
          "sourceSecretRef": {
            "name": "wandb-api-key",
            "namespace": "axisml-system"
          },
          "type": "Opaque"
        }
      ],
      "serviceAccounts": [
        {
          "imagePullSecrets": [
            "registry-pull"
          ],
          "name": "trainer",
          "rbac": {
            "roleRefs": [
              {
                "kind": "ClusterRole",
                "name": "edit"
              }
            ]
          }
        }
      ]
    },
    "kubernetesNamespace": "axisml-team-vision",
    "labels": {
      "team": "vision"
    },
    "memberCount": 8,
    "onlineServices": 1,
    "owner": "li.wei",
    "phase": "Active",
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ],
    "status": {
      "conditions": [
        {
          "lastTransitionTime": "2026-06-28T09:30:00Z",
          "message": "Namespace and quota provisioned.",
          "reason": "Provisioned",
          "status": "True",
          "type": "Ready"
        }
      ],
      "message": "Tenant is active.",
      "quotas": [
        {
          "pool": "gpu-a100",
          "units": [
            {
              "quantity": 4,
              "unitName": "a100-2x",
              "used": 3
            }
          ]
        }
      ]
    },
    "suspended": false,
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "TenantCreateRequest": {
    "description": "Computer-vision model training and inference team.",
    "displayName": "Vision Team",
    "identifier": "team-vision",
    "initialAdmin": "li.wei@example.com",
    "kubernetesNamespace": "axisml-team-vision",
    "labels": {
      "team": "vision"
    },
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x"
          }
        ]
      }
    ]
  },
  "TenantList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "activeExperimentRuns": 2,
        "activeJobRuns": 3,
        "annotations": {
          "axisml.io/created-by": "system-admin"
        },
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Computer-vision model training and inference team.",
        "displayName": "Vision Team",
        "identifier": "team-vision",
        "initResources": {
          "configMaps": [
            {
              "name": "shared-config",
              "sourceConfigMapRef": {
                "name": "shared-config",
                "namespace": "axisml-system"
              }
            }
          ],
          "imagePullSecrets": [
            {
              "name": "registry-pull",
              "sourceSecretRef": {
                "name": "registry-pull",
                "namespace": "axisml-system"
              }
            }
          ],
          "secrets": [
            {
              "name": "wandb-api-key",
              "sourceSecretRef": {
                "name": "wandb-api-key",
                "namespace": "axisml-system"
              },
              "type": "Opaque"
            }
          ],
          "serviceAccounts": [
            {
              "imagePullSecrets": [
                "registry-pull"
              ],
              "name": "trainer",
              "rbac": {
                "roleRefs": [
                  {
                    "kind": "ClusterRole",
                    "name": "edit"
                  }
                ]
              }
            }
          ]
        },
        "kubernetesNamespace": "axisml-team-vision",
        "labels": {
          "team": "vision"
        },
        "memberCount": 8,
        "onlineServices": 1,
        "owner": "li.wei",
        "phase": "Active",
        "quotas": [
          {
            "pool": "gpu-a100",
            "units": [
              {
                "quantity": 4,
                "unitName": "a100-2x"
              }
            ]
          }
        ],
        "status": {
          "conditions": [
            {
              "lastTransitionTime": "2026-06-28T09:30:00Z",
              "message": "Namespace and quota provisioned.",
              "reason": "Provisioned",
              "status": "True",
              "type": "Ready"
            }
          ],
          "message": "Tenant is active.",
          "quotas": [
            {
              "pool": "gpu-a100",
              "units": [
                {
                  "quantity": 4,
                  "unitName": "a100-2x",
                  "used": 3
                }
              ]
            }
          ]
        },
        "suspended": false,
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "TenantPatchRequest": {
    "description": "Updated team description.",
    "displayName": "Vision Team (core)"
  },
  "TenantStatus": {
    "conditions": [
      {
        "lastTransitionTime": "2026-06-28T09:30:00Z",
        "message": "Namespace and quota provisioned.",
        "reason": "Provisioned",
        "status": "True",
        "type": "Ready"
      }
    ],
    "message": "Tenant is active.",
    "quotas": [
      {
        "pool": "gpu-a100",
        "units": [
          {
            "quantity": 4,
            "unitName": "a100-2x",
            "used": 3
          }
        ]
      }
    ]
  },
  "TensorBoard": {
    "createdAt": "2026-06-20T08:00:00Z",
    "message": "TensorBoard is serving.",
    "name": "bert-finetune-tb",
    "phase": "Running",
    "url": "https://tb.axisml.io/team-nlp/bert-finetune"
  },
  "TensorBoardRequest": {
    "runs": [
      "bert-finetune-3",
      "bert-finetune-5"
    ]
  },
  "TrafficPolicy": {
    "accessUrl": "https://infer.axisml.io/services/team-vision/resnet-serving/",
    "backends": [
      {
        "actualPct": 90,
        "ready": true,
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 90
      },
      {
        "actualPct": 10,
        "ready": true,
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 10
      }
    ],
    "canaryPercent": 10,
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "Canary traffic split for the ResNet-50 online inference service.",
    "displayName": "ResNet inference traffic",
    "endpoint": {
      "hostname": "infer.axisml.io",
      "path": "/services/team-vision/resnet-serving/"
    },
    "id": "d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f90",
    "message": "Routing 90/10 between stable and canary.",
    "mode": "canary",
    "name": "resnet-serving",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "phase": "Ready",
    "tenantDisplayName": "Vision Team",
    "tenantName": "team-vision",
    "updatedAt": "2026-06-28T09:30:00Z"
  },
  "TrafficPolicyBackend": {
    "actualPct": 90,
    "ready": true,
    "role": "stable",
    "serviceName": "resnet-serving-v1",
    "weight": 90
  },
  "TrafficPolicyBackendSpec": {
    "role": "canary",
    "serviceName": "resnet-serving-v2",
    "weight": 10
  },
  "TrafficPolicyCreateRequest": {
    "backends": [
      {
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 90
      },
      {
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 10
      }
    ],
    "canaryPercent": 10,
    "description": "Canary traffic split for the ResNet-50 online inference service.",
    "displayName": "ResNet inference traffic",
    "endpoint": {
      "hostname": "infer.axisml.io",
      "path": "/services/team-vision/resnet-serving/"
    },
    "mode": "canary",
    "name": "resnet-serving"
  },
  "TrafficPolicyEndpoint": {
    "hostname": "infer.axisml.io",
    "path": "/services/team-vision/resnet-serving/"
  },
  "TrafficPolicyList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "accessUrl": "https://infer.axisml.io/services/team-vision/resnet-serving/",
        "backends": [
          {
            "actualPct": 90,
            "ready": true,
            "role": "stable",
            "serviceName": "resnet-serving-v1",
            "weight": 90
          },
          {
            "actualPct": 10,
            "ready": true,
            "role": "canary",
            "serviceName": "resnet-serving-v2",
            "weight": 10
          }
        ],
        "canaryPercent": 10,
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "Canary traffic split for the ResNet-50 online inference service.",
        "displayName": "ResNet inference traffic",
        "endpoint": {
          "hostname": "infer.axisml.io",
          "path": "/services/team-vision/resnet-serving/"
        },
        "id": "d4e5f6a7-8b9c-0d1e-2f3a-4b5c6d7e8f90",
        "message": "Routing 90/10 between stable and canary.",
        "mode": "canary",
        "name": "resnet-serving",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "phase": "Ready",
        "tenantDisplayName": "Vision Team",
        "tenantName": "team-vision",
        "updatedAt": "2026-06-28T09:30:00Z"
      }
    ],
    "partial": false
  },
  "TrafficPolicyPatchRequest": {
    "description": "Updated description.",
    "displayName": "ResNet inference traffic (v2)"
  },
  "TrafficPolicySplitRequest": {
    "backends": [
      {
        "role": "stable",
        "serviceName": "resnet-serving-v1",
        "weight": 75
      },
      {
        "role": "canary",
        "serviceName": "resnet-serving-v2",
        "weight": 25
      }
    ],
    "canaryPercent": 25
  },
  "User": {
    "createdAt": "2026-06-20T08:00:00Z",
    "disabled": false,
    "displayName": "Li Wei",
    "email": "li.wei@axisml.io",
    "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "mustChangePassword": false,
    "updatedAt": "2026-06-28T09:30:00Z",
    "username": "li.wei"
  },
  "UserCreateRequest": {
    "displayName": "Li Wei",
    "email": "li.wei@axisml.io",
    "password": "S3cure-pass",
    "username": "li.wei"
  },
  "UserPatchRequest": {
    "disabled": false,
    "displayName": "Li Wei (Vision Lead)",
    "email": "li.wei@axisml.io"
  },
  "UserSummary": {
    "displayName": "Li Wei",
    "email": "li.wei@axisml.io",
    "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "username": "li.wei"
  },
  "UserSummaryList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "displayName": "Li Wei",
        "email": "li.wei@axisml.io",
        "id": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "username": "li.wei"
      }
    ]
  },
  "UserTenantRole": {
    "roleName": "admin",
    "tenantName": "team-vision"
  },
  "Workspace": {
    "args": [
      "--NotebookApp.token="
    ],
    "command": [
      "start-notebook.sh"
    ],
    "computeNamespace": "axisml-team-vision",
    "containerPort": 8888,
    "createdAt": "2026-06-20T08:00:00Z",
    "description": "JupyterLab interactive development environment.",
    "desiredState": "Running",
    "displayName": "Vision team dev environment",
    "endpoint": {
      "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
      "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local",
      "tools": [
        {
          "label": "JupyterLab",
          "name": "jupyter",
          "url": "https://axisml.example.com/ws/team-vision/notebook-dev/lab"
        },
        {
          "label": "VS Code",
          "name": "vscode",
          "url": "https://axisml.example.com/ws/team-vision/notebook-dev/vscode/"
        },
        {
          "label": "Terminal",
          "name": "terminal",
          "url": "https://axisml.example.com/ws/team-vision/notebook-dev/terminals/1"
        }
      ]
    },
    "env": [
      {
        "name": "JUPYTER_ENABLE_LAB",
        "value": "yes"
      }
    ],
    "id": "f1e2d3c4-5b6a-4798-8c0d-1e2f3a4b5c6d",
    "image": "registry.axisml.io/dev/jupyter:3.0.0",
    "lastStartedAt": "2026-06-28T09:00:00Z",
    "lifecycle": {
      "idleTimeoutSeconds": 3600
    },
    "message": "Workspace is ready.",
    "name": "notebook-dev",
    "namespace": "team-vision",
    "owner": "li.wei",
    "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
    "phase": "Running",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "readyReplicas": 1,
    "replicas": 1,
    "resources": {
      "cpu": "4",
      "memory": "32Gi",
      "nvidia.com/gpu": "1"
    },
    "tenantDisplayName": "Vision Team",
    "tenantName": "team-vision",
    "unitName": "a100-1x",
    "updatedAt": "2026-06-28T09:30:00Z",
    "volumes": [
      {
        "mountPath": "/home/jovyan/work",
        "name": "notebook-data",
        "used": "12Gi"
      }
    ]
  },
  "WorkspaceCreateRequest": {
    "containerPort": 8888,
    "description": "JupyterLab interactive development environment.",
    "displayName": "Vision team dev environment",
    "image": "registry.axisml.io/dev/jupyter:3.0.0",
    "lifecycle": {
      "idleTimeoutSeconds": 3600
    },
    "name": "notebook-dev",
    "poolName": "gpu-a100",
    "quota": "team-vision",
    "unitName": "a100-1x",
    "volumes": [
      {
        "mountPath": "/home/jovyan/work",
        "name": "notebook-data"
      }
    ]
  },
  "WorkspaceEndpoint": {
    "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
    "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local",
    "tools": [
      {
        "label": "JupyterLab",
        "name": "jupyter",
        "url": "https://axisml.example.com/ws/team-vision/notebook-dev/lab"
      },
      {
        "label": "VS Code",
        "name": "vscode",
        "url": "https://axisml.example.com/ws/team-vision/notebook-dev/vscode/"
      },
      {
        "label": "Terminal",
        "name": "terminal",
        "url": "https://axisml.example.com/ws/team-vision/notebook-dev/terminals/1"
      }
    ]
  },
  "WorkspaceImage": {
    "defaultPort": 8888,
    "description": "JupyterLab data-science environment (public).",
    "displayName": "JupyterLab",
    "kind": "jupyter",
    "public": true,
    "ref": "registry.axisml.io/dev/jupyter:3.0.0"
  },
  "WorkspaceImageList": {
    "count": 3,
    "items": [
      {
        "defaultPort": 8888,
        "description": "JupyterLab data-science environment (public).",
        "displayName": "JupyterLab",
        "kind": "jupyter",
        "public": true,
        "ref": "registry.axisml.io/dev/jupyter:3.0.0"
      },
      {
        "defaultPort": 8888,
        "description": "CUDA 12.1 + PyTorch 2.3 training image.",
        "displayName": "PyTorch",
        "kind": "jupyter",
        "public": true,
        "ref": "registry.axisml.io/dev/pytorch:2.3.0"
      },
      {
        "defaultPort": 8080,
        "description": "VS Code (code-server) development environment (public).",
        "displayName": "VS Code",
        "kind": "vscode",
        "public": true,
        "ref": "registry.axisml.io/dev/code-server:4.22"
      }
    ]
  },
  "WorkspaceLifecycle": {
    "idleTimeoutSeconds": 3600
  },
  "WorkspaceList": {
    "continueToken": "",
    "count": 1,
    "items": [
      {
        "args": [
          "--NotebookApp.token="
        ],
        "command": [
          "start-notebook.sh"
        ],
        "computeNamespace": "axisml-team-vision",
        "containerPort": 8888,
        "createdAt": "2026-06-20T08:00:00Z",
        "description": "JupyterLab interactive development environment.",
        "desiredState": "Running",
        "displayName": "Vision team dev environment",
        "endpoint": {
          "accessUrl": "https://axisml.example.com/ws/team-vision/notebook-dev/",
          "internalDns": "notebook-dev.axisml-team-vision.svc.cluster.local",
          "tools": [
            {
              "label": "JupyterLab",
              "name": "jupyter",
              "url": "https://axisml.example.com/ws/team-vision/notebook-dev/lab"
            },
            {
              "label": "VS Code",
              "name": "vscode",
              "url": "https://axisml.example.com/ws/team-vision/notebook-dev/vscode/"
            },
            {
              "label": "Terminal",
              "name": "terminal",
              "url": "https://axisml.example.com/ws/team-vision/notebook-dev/terminals/1"
            }
          ]
        },
        "env": [
          {
            "name": "JUPYTER_ENABLE_LAB",
            "value": "yes"
          }
        ],
        "id": "f1e2d3c4-5b6a-4798-8c0d-1e2f3a4b5c6d",
        "image": "registry.axisml.io/dev/jupyter:3.0.0",
        "lastStartedAt": "2026-06-28T09:00:00Z",
        "lifecycle": {
          "idleTimeoutSeconds": 3600
        },
        "message": "Workspace is ready.",
        "name": "notebook-dev",
        "namespace": "team-vision",
        "owner": "li.wei",
        "ownerId": "3a2b1c0d-4e5f-6789-abcd-ef0123456789",
        "phase": "Running",
        "poolName": "gpu-a100",
        "quota": "team-vision",
        "readyReplicas": 1,
        "replicas": 1,
        "resources": {
          "cpu": "4",
          "memory": "32Gi",
          "nvidia.com/gpu": "1"
        },
        "tenantDisplayName": "Vision Team",
        "tenantName": "team-vision",
        "unitName": "a100-1x",
        "updatedAt": "2026-06-28T09:30:00Z",
        "volumes": [
          {
            "mountPath": "/home/jovyan/work",
            "name": "notebook-data",
            "used": "12Gi"
          }
        ]
      }
    ],
    "partial": false
  },
  "WorkspacePatchRequest": {
    "description": "Updated description.",
    "displayName": "Vision team dev environment (v2)",
    "lifecycle": {
      "idleTimeoutSeconds": 7200
    }
  },
  "WorkspaceTool": {
    "label": "JupyterLab",
    "name": "jupyter",
    "url": "https://axisml.example.com/ws/team-vision/notebook-dev/lab"
  },
  "WorkspaceVolume": {
    "mountPath": "/home/jovyan/work",
    "name": "notebook-data",
    "used": "12Gi"
  },
};

/** Typed accessor: ex<Job>("Job"). Throws if the schema carries no example. */
export function ex<T>(name: string): T {
  const value = examples[name];
  if (value === undefined) {
    throw new Error(`mock example missing for schema "${name}" — run pnpm run gen:mock`);
  }
  return structuredClone(value) as T;
}
