{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "axisml.fullname" . }}-database
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "database") | nindent 4 }}
spec:
  serviceName: {{ include "axisml.fullname" . }}-database
  replicas: 1
  selector:
    matchLabels:
      {{- include "axisml.componentSelectorLabels" (dict "context" . "component" "database") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axisml.componentLabels" (dict "context" . "component" "database") | nindent 8 }}
    spec:
      containers:
        - name: database
          image: {{ include "axisml.image" (dict "imageRoot" .Values.database.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: {{ .Values.database.port }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.auth.password | quote }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.database.persistence.storageClass .Values.global.storageClass }}
        storageClassName: {{ .Values.database.persistence.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.persistence.size }}
{{- end }}
