// openapi-gen renders an OpenAPI 3.0 description of the compute HTTP API
// to docs/openapi.yaml.
//
// Schemas are derived from the same Go request/response structs the runtime
// handlers use, so the spec stays in lock-step with the code. Routes and
// operations are listed explicitly here (single source of truth) rather than
// scraped from the gin router so the file is reviewable.
//
// Run from the component root:
//
//	go run ./cmd/openapi-gen -o docs/openapi.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"sigs.k8s.io/yaml"

	"github.com/axisml/axisml/components/compute/internal/job"
	"github.com/axisml/axisml/components/compute/internal/quota"
	"github.com/axisml/axisml/components/compute/internal/resourcepool"
	"github.com/axisml/axisml/components/compute/internal/resourceunit"
	"github.com/axisml/axisml/components/compute/internal/server"
	servicemod "github.com/axisml/axisml/components/compute/internal/service"
	"github.com/axisml/axisml/components/compute/internal/tenant"
)

// version mirrors deploy/helm/axisml-system/Chart.yaml appVersion. Tracked
// manually here; the make target syncs it via -ldflags from the Makefile.
var version = "0.1.0"

func main() {
	out := flag.String("o", "docs/openapi.yaml", "output path")
	v := flag.String("version", version, "info.version field")
	flag.Parse()

	doc := buildDocument(*v)

	yml, err := yaml.Marshal(doc)
	if err != nil {
		fail("marshal: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	header := []byte("# Code generated by cmd/openapi-gen. DO NOT EDIT.\n# Regenerate with: make openapi\n")
	if err := os.WriteFile(*out, append(header, yml...), 0o644); err != nil {
		fail("write: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "openapi-gen: "+format+"\n", args...)
	os.Exit(1)
}

// --- OpenAPI 3.0 types (subset we emit) -------------------------------------

type document struct {
	OpenAPI    string              `json:"openapi"`
	Info       info                `json:"info"`
	Servers    []serverEntry       `json:"servers,omitempty"`
	Tags       []tagEntry          `json:"tags,omitempty"`
	Paths      map[string]pathItem `json:"paths"`
	Components componentsBlock     `json:"components"`
}

type info struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

type serverEntry struct {
	URL         string `json:"url"`
	Description string `json:"description,omitempty"`
}

type tagEntry struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

type pathItem struct {
	Get    *operation `json:"get,omitempty"`
	Post   *operation `json:"post,omitempty"`
	Patch  *operation `json:"patch,omitempty"`
	Delete *operation `json:"delete,omitempty"`
	Put    *operation `json:"put,omitempty"`
}

type operation struct {
	Tags        []string            `json:"tags,omitempty"`
	Summary     string              `json:"summary,omitempty"`
	OperationID string              `json:"operationId,omitempty"`
	Parameters  []parameter         `json:"parameters,omitempty"`
	RequestBody *requestBody        `json:"requestBody,omitempty"`
	Responses   map[string]response `json:"responses"`
}

type parameter struct {
	Name        string  `json:"name"`
	In          string  `json:"in"`
	Required    bool    `json:"required,omitempty"`
	Description string  `json:"description,omitempty"`
	Schema      *schema `json:"schema,omitempty"`
}

type requestBody struct {
	Required bool                 `json:"required,omitempty"`
	Content  map[string]mediaType `json:"content"`
}

type response struct {
	Description string               `json:"description"`
	Content     map[string]mediaType `json:"content,omitempty"`
}

type mediaType struct {
	Schema *schema `json:"schema,omitempty"`
}

type componentsBlock struct {
	Schemas map[string]*schema `json:"schemas"`
}

// schema is a minimal subset of OpenAPI 3.0 schema. Only fields we emit.
type schema struct {
	Ref                  string             `json:"$ref,omitempty"`
	Type                 string             `json:"type,omitempty"`
	Format               string             `json:"format,omitempty"`
	Description          string             `json:"description,omitempty"`
	Required             []string           `json:"required,omitempty"`
	Properties           map[string]*schema `json:"properties,omitempty"`
	Items                *schema            `json:"items,omitempty"`
	AdditionalProperties *schema            `json:"additionalProperties,omitempty"`
	Nullable             bool               `json:"nullable,omitempty"`
	Enum                 []string           `json:"enum,omitempty"`
	Minimum              *float64           `json:"minimum,omitempty"`
	MinItems             *int               `json:"minItems,omitempty"`
	Example              any                `json:"example,omitempty"`
}

func ref(name string) *schema { return &schema{Ref: "#/components/schemas/" + name} }

// --- Reflection-based schema generator --------------------------------------

type generator struct {
	defs map[string]*schema
	// inProgress tracks types currently being generated to break cycles.
	inProgress map[reflect.Type]string
}

func newGenerator() *generator {
	return &generator{defs: map[string]*schema{}, inProgress: map[reflect.Type]string{}}
}

// register derives a schema for v and stores it under the provided component
// name (so handlers can reference it as #/components/schemas/<name>). For
// named struct types we call structSchema directly so the slot holds the
// expanded schema rather than a $ref to itself.
func (g *generator) register(name string, v any) {
	t := reflect.TypeOf(v)
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	g.inProgress[t] = name
	var s *schema
	if ws := wellKnown(t); ws != nil {
		s = ws
	} else if t.Kind() == reflect.Struct {
		s = g.structSchema(t)
	} else {
		s = g.schemaForType(t)
	}
	g.defs[name] = s
	delete(g.inProgress, t)
}

// schemaForType is the workhorse. For named struct types it emits a $ref
// (defining the target lazily) so we get a tidy components/schemas section
// instead of inline duplication.
func (g *generator) schemaForType(t reflect.Type) *schema {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if s := wellKnown(t); s != nil {
		return s
	}
	switch t.Kind() {
	case reflect.String:
		return &schema{Type: "string"}
	case reflect.Bool:
		return &schema{Type: "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return &schema{Type: "integer", Format: intFormat(t)}
	case reflect.Float32, reflect.Float64:
		return &schema{Type: "number", Format: floatFormat(t)}
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 { // []byte → base64 string
			return &schema{Type: "string", Format: "byte"}
		}
		return &schema{Type: "array", Items: g.schemaForType(t.Elem())}
	case reflect.Map:
		return &schema{Type: "object", AdditionalProperties: g.schemaForType(t.Elem())}
	case reflect.Struct:
		// Anonymous structs are inlined; named ones become $ref.
		if t.Name() != "" {
			name := componentName(t)
			if existing, ok := g.inProgress[t]; ok {
				return ref(existing)
			}
			if _, defined := g.defs[name]; defined {
				return ref(name)
			}
			g.inProgress[t] = name
			s := g.structSchema(t)
			g.defs[name] = s
			delete(g.inProgress, t)
			return ref(name)
		}
		return g.structSchema(t)
	case reflect.Interface:
		return &schema{} // free-form
	}
	return &schema{}
}

func (g *generator) structSchema(t reflect.Type) *schema {
	out := &schema{Type: "object", Properties: map[string]*schema{}}
	var required []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		// Embedded promotion: flatten anonymous struct fields.
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Tag.Get("json") == "" {
			sub := g.structSchema(f.Type)
			for k, v := range sub.Properties {
				out.Properties[k] = v
			}
			required = append(required, sub.Required...)
			continue
		}
		jsonTag := f.Tag.Get("json")
		if jsonTag == "-" {
			continue
		}
		name, opts := splitTag(jsonTag)
		if name == "" {
			name = f.Name
		}
		fs := g.schemaForType(f.Type)
		if isPtr(f.Type) {
			fs.Nullable = true
		}
		out.Properties[name] = fs
		if isRequired(f.Tag.Get("binding"), opts, f.Type) {
			required = append(required, name)
		}
	}
	if len(required) > 0 {
		sort.Strings(required)
		out.Required = required
	}
	return out
}

func splitTag(tag string) (name string, opts []string) {
	parts := strings.Split(tag, ",")
	if len(parts) == 0 {
		return "", nil
	}
	return parts[0], parts[1:]
}

func isRequired(binding string, jsonOpts []string, t reflect.Type) bool {
	for _, o := range jsonOpts {
		if o == "omitempty" {
			return false
		}
	}
	if isPtr(t) {
		return false
	}
	for _, b := range strings.Split(binding, ",") {
		if strings.TrimSpace(b) == "required" {
			return true
		}
	}
	return false
}

func isPtr(t reflect.Type) bool { return t.Kind() == reflect.Ptr }

func intFormat(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Int32, reflect.Uint32, reflect.Int16, reflect.Uint16, reflect.Int8, reflect.Uint8:
		return "int32"
	case reflect.Int64, reflect.Uint64:
		return "int64"
	}
	return ""
}

func floatFormat(t reflect.Type) string {
	if t.Kind() == reflect.Float32 {
		return "float"
	}
	return "double"
}

// componentName produces a stable, human-readable name like
// "tenant.CreateInput" → "TenantCreateInput". For the three operator API
// packages (which all end in "/api/v1alpha1"), we pull the operator name
// from the path so MLJob/MLService/Tenant types don't collide on the same
// "V1alpha1" prefix.
func componentName(t reflect.Type) string {
	pkg := t.PkgPath()
	if prefix, ok := operatorAPIPrefix(pkg); ok {
		// Avoid e.g. "MLJobMLJobSpec" — keep just "MLJobSpec" if the type name
		// already starts with the prefix.
		if strings.HasPrefix(t.Name(), prefix) {
			return t.Name()
		}
		return prefix + t.Name()
	}
	last := pkg
	if i := strings.LastIndex(pkg, "/"); i >= 0 {
		last = pkg[i+1:]
	}
	// Compute's own service package is named "service"; collapse to MLService
	// so it reads as a noun rather than a generic word.
	if pkg == "github.com/axisml/axisml/components/compute/internal/service" {
		last = "MLService"
	}
	if last == "" {
		return t.Name()
	}
	return capitalize(last) + t.Name()
}

// operatorAPIPrefix maps the three operator API packages to a prefix that
// includes the operator name. The path looks like
// ".../components/operators/<op>-operator/api/v1alpha1".
func operatorAPIPrefix(pkg string) (string, bool) {
	const opRoot = "components/operators/"
	i := strings.Index(pkg, opRoot)
	if i < 0 {
		return "", false
	}
	rest := pkg[i+len(opRoot):]
	parts := strings.Split(rest, "/")
	if len(parts) < 1 {
		return "", false
	}
	op := strings.TrimSuffix(parts[0], "-operator")
	switch op {
	case "mljob":
		return "MLJob", true
	case "mlservice":
		return "MLService", true
	case "tenant":
		return "Tenant", true
	}
	return capitalize(op), true
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// wellKnown maps Go types that don't have a useful struct-reflective shape
// (or that we want to render with a specific OpenAPI flavor) to a fixed
// schema. Returning nil falls through to the default reflection path.
func wellKnown(t reflect.Type) *schema {
	switch t {
	case reflect.TypeOf(time.Time{}):
		return &schema{Type: "string", Format: "date-time"}
	case reflect.TypeOf(uuid.UUID{}):
		return &schema{Type: "string", Format: "uuid"}
	case reflect.TypeOf(resource.Quantity{}):
		return &schema{
			Type:        "string",
			Description: "Kubernetes resource.Quantity (e.g. \"500m\", \"2Gi\", \"4\").",
		}
	case reflect.TypeOf(datatypes.JSON{}):
		return &schema{Type: "object", Description: "Free-form JSON object."}
	case reflect.TypeOf(corev1.ResourceList{}):
		return &schema{
			Type: "object",
			AdditionalProperties: &schema{
				Type:        "string",
				Description: "Kubernetes resource.Quantity.",
			},
			Description: "Map of resource name (cpu, memory, nvidia.com/gpu, …) to resource.Quantity.",
		}
	}
	// metav1.Duration has a single String-marshalling Duration field; render it
	// as a string instead of an object.
	if t.Kind() == reflect.Struct && t.PkgPath() == "k8s.io/apimachinery/pkg/apis/meta/v1" && t.Name() == "Duration" {
		return &schema{Type: "string", Description: "Go duration string (e.g. \"30s\", \"5m\")."}
	}
	return nil
}

// --- Document construction --------------------------------------------------

func buildDocument(version string) *document {
	g := newGenerator()

	// Core component schemas (referenced from operations).
	g.register("Problem", server.Problem{})
	g.register("TenantCreateInput", tenant.CreateInput{})
	g.register("TenantUpdateInput", tenant.UpdateInput{})
	g.register("TenantView", tenant.View{})
	g.register("ResourcepoolCreateInput", resourcepool.CreateInput{})
	g.register("ResourcepoolUpdateInput", resourcepool.UpdateInput{})
	g.register("ResourcepoolView", resourcepool.View{})
	g.register("ResourceunitCreateInput", resourceunit.CreateInput{})
	g.register("ResourceunitUpdateInput", resourceunit.UpdateInput{})
	g.register("ResourceunitView", resourceunit.View{})
	g.register("QuotaCreateInput", quota.CreateInput{})
	g.register("QuotaUpdateInput", quota.UpdateInput{})
	g.register("QuotaView", quota.View{})
	g.register("JobCreateInput", job.CreateInput{})
	g.register("JobView", job.View{})
	g.register("MLServiceCreateInput", servicemod.CreateInput{})
	g.register("MLServiceScaleInput", servicemod.ScaleInput{})
	g.register("MLServiceView", servicemod.View{})

	// Generic list envelope: {items: [], total: int}. We emit one envelope per
	// resource so $ref to the right item type is preserved.
	listEnvelope := func(itemRef string) *schema {
		return &schema{
			Type:     "object",
			Required: []string{"items", "total"},
			Properties: map[string]*schema{
				"items": {Type: "array", Items: ref(itemRef)},
				"total": {Type: "integer", Format: "int64"},
			},
		}
	}
	g.defs["TenantList"] = listEnvelope("TenantView")
	g.defs["ResourcepoolList"] = listEnvelope("ResourcepoolView")
	g.defs["ResourceunitList"] = listEnvelope("ResourceunitView")
	g.defs["QuotaList"] = listEnvelope("QuotaView")
	g.defs["JobList"] = listEnvelope("JobView")
	g.defs["MLServiceList"] = listEnvelope("MLServiceView")

	tags := []tagEntry{
		{Name: "tenants", Description: "Tenant CRUD and lifecycle."},
		{Name: "resource-pools", Description: "Cluster-scoped resource pool registry."},
		{Name: "resource-units", Description: "Reusable CPU/GPU/memory recipes scoped to a pool."},
		{Name: "quotas", Description: "Per-(tenant, pool) ElasticQuota records."},
		{Name: "jobs", Description: "MLJob CRUD per tenant."},
		{Name: "services", Description: "MLService CRUD per tenant."},
		{Name: "system", Description: "Liveness and readiness probes."},
	}

	paths := map[string]pathItem{}

	// --- system ---
	stringResp := func(desc string) response {
		return response{
			Description: desc,
			Content: map[string]mediaType{
				"text/plain": {Schema: &schema{Type: "string"}},
			},
		}
	}
	paths["/healthz"] = pathItem{Get: &operation{
		Tags: []string{"system"}, Summary: "Liveness probe", OperationID: "healthz",
		Responses: map[string]response{"200": stringResp("ok")},
	}}
	paths["/readyz"] = pathItem{Get: &operation{
		Tags: []string{"system"}, Summary: "Readiness probe", OperationID: "readyz",
		Responses: map[string]response{
			"200": stringResp("ok"),
			"503": stringResp("dependency not yet ready"),
		},
	}}

	// --- shared parameter helpers ---
	pathParam := func(name, desc string) parameter {
		return parameter{Name: name, In: "path", Required: true, Description: desc, Schema: &schema{Type: "string"}}
	}
	queryParam := func(name, desc string, sch *schema) parameter {
		return parameter{Name: name, In: "query", Description: desc, Schema: sch}
	}
	limitParam := queryParam("limit", "Page size (1–200, default 50).", &schema{Type: "integer", Format: "int32"})
	offsetParam := queryParam("offset", "Number of items to skip.", &schema{Type: "integer", Format: "int32"})

	jsonBody := func(refName string) *requestBody {
		return &requestBody{
			Required: true,
			Content:  map[string]mediaType{"application/json": {Schema: ref(refName)}},
		}
	}
	jsonResp := func(desc, refName string) response {
		return response{
			Description: desc,
			Content:     map[string]mediaType{"application/json": {Schema: ref(refName)}},
		}
	}
	noContent := response{Description: "Deleted (idempotent)."}

	defaultErrors := func() map[string]response {
		return map[string]response{
			"400":     jsonResp("Validation error.", "Problem"),
			"401":     jsonResp("Unauthorized.", "Problem"),
			"403":     jsonResp("Forbidden.", "Problem"),
			"404":     jsonResp("Not found.", "Problem"),
			"409":     jsonResp("Conflict.", "Problem"),
			"422":     jsonResp("Quota exceeded.", "Problem"),
			"default": jsonResp("Unexpected error.", "Problem"),
		}
	}
	merge := func(base map[string]response, extras map[string]response) map[string]response {
		out := map[string]response{}
		for k, v := range base {
			out[k] = v
		}
		for k, v := range extras {
			out[k] = v
		}
		return out
	}

	// --- tenants ---
	paths["/api/v1/tenants"] = pathItem{
		Post: &operation{
			Tags: []string{"tenants"}, Summary: "Create a tenant", OperationID: "createTenant",
			RequestBody: jsonBody("TenantCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Tenant created.", "TenantView"),
			}),
		},
		Get: &operation{
			Tags: []string{"tenants"}, Summary: "List tenants", OperationID: "listTenants",
			Parameters: []parameter{limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Tenant page.", "TenantList"),
			}),
		},
	}
	paths["/api/v1/tenants/{tenant}"] = pathItem{
		Get: &operation{
			Tags: []string{"tenants"}, Summary: "Get tenant", OperationID: "getTenant",
			Parameters: []parameter{pathParam("tenant", "Tenant name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Tenant.", "TenantView"),
			}),
		},
		Patch: &operation{
			Tags: []string{"tenants"}, Summary: "Patch tenant", OperationID: "updateTenant",
			Parameters:  []parameter{pathParam("tenant", "Tenant name.")},
			RequestBody: jsonBody("TenantUpdateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Updated tenant.", "TenantView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"tenants"}, Summary: "Delete tenant", OperationID: "deleteTenant",
			Parameters: []parameter{pathParam("tenant", "Tenant name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}
	paths["/api/v1/tenants/{tenant}/suspend"] = pathItem{Post: &operation{
		Tags: []string{"tenants"}, Summary: "Suspend tenant", OperationID: "suspendTenant",
		Parameters: []parameter{pathParam("tenant", "Tenant name.")},
		Responses: merge(defaultErrors(), map[string]response{
			"200": jsonResp("Suspended.", "TenantView"),
		}),
	}}
	paths["/api/v1/tenants/{tenant}/unsuspend"] = pathItem{Post: &operation{
		Tags: []string{"tenants"}, Summary: "Unsuspend tenant", OperationID: "unsuspendTenant",
		Parameters: []parameter{pathParam("tenant", "Tenant name.")},
		Responses: merge(defaultErrors(), map[string]response{
			"200": jsonResp("Unsuspended.", "TenantView"),
		}),
	}}

	// --- resource pools ---
	paths["/api/v1/resource-pools"] = pathItem{
		Post: &operation{
			Tags: []string{"resource-pools"}, Summary: "Create a resource pool", OperationID: "createResourcePool",
			RequestBody: jsonBody("ResourcepoolCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Created.", "ResourcepoolView"),
			}),
		},
		Get: &operation{
			Tags: []string{"resource-pools"}, Summary: "List resource pools", OperationID: "listResourcePools",
			Parameters: []parameter{limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Page.", "ResourcepoolList"),
			}),
		},
	}
	paths["/api/v1/resource-pools/{pool}"] = pathItem{
		Get: &operation{
			Tags: []string{"resource-pools"}, Summary: "Get resource pool", OperationID: "getResourcePool",
			Parameters: []parameter{pathParam("pool", "Resource pool name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Resource pool.", "ResourcepoolView"),
			}),
		},
		Patch: &operation{
			Tags: []string{"resource-pools"}, Summary: "Patch resource pool", OperationID: "updateResourcePool",
			Parameters:  []parameter{pathParam("pool", "Resource pool name.")},
			RequestBody: jsonBody("ResourcepoolUpdateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Updated.", "ResourcepoolView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"resource-pools"}, Summary: "Delete resource pool", OperationID: "deleteResourcePool",
			Parameters: []parameter{pathParam("pool", "Resource pool name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}

	// --- resource units (under a pool) ---
	paths["/api/v1/resource-pools/{pool}/resource-units"] = pathItem{
		Post: &operation{
			Tags: []string{"resource-units"}, Summary: "Create a resource unit", OperationID: "createResourceUnit",
			Parameters:  []parameter{pathParam("pool", "Resource pool name.")},
			RequestBody: jsonBody("ResourceunitCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Created.", "ResourceunitView"),
			}),
		},
		Get: &operation{
			Tags: []string{"resource-units"}, Summary: "List resource units in a pool", OperationID: "listResourceUnits",
			Parameters: []parameter{pathParam("pool", "Resource pool name."), limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Page.", "ResourceunitList"),
			}),
		},
	}
	paths["/api/v1/resource-pools/{pool}/resource-units/{unit}"] = pathItem{
		Get: &operation{
			Tags: []string{"resource-units"}, Summary: "Get resource unit", OperationID: "getResourceUnit",
			Parameters: []parameter{pathParam("pool", "Resource pool name."), pathParam("unit", "Resource unit name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Resource unit.", "ResourceunitView"),
			}),
		},
		Patch: &operation{
			Tags: []string{"resource-units"}, Summary: "Patch resource unit", OperationID: "updateResourceUnit",
			Parameters: []parameter{
				pathParam("pool", "Resource pool name."),
				pathParam("unit", "Resource unit name."),
			},
			RequestBody: jsonBody("ResourceunitUpdateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Updated.", "ResourceunitView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"resource-units"}, Summary: "Delete resource unit", OperationID: "deleteResourceUnit",
			Parameters: []parameter{pathParam("pool", "Resource pool name."), pathParam("unit", "Resource unit name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}

	// --- quotas (per tenant) ---
	paths["/api/v1/tenants/{tenant}/quotas"] = pathItem{
		Post: &operation{
			Tags: []string{"quotas"}, Summary: "Create a quota", OperationID: "createQuota",
			Parameters:  []parameter{pathParam("tenant", "Tenant name.")},
			RequestBody: jsonBody("QuotaCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Created.", "QuotaView"),
			}),
		},
		Get: &operation{
			Tags: []string{"quotas"}, Summary: "List quotas for a tenant", OperationID: "listQuotas",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Page.", "QuotaList"),
			}),
		},
	}
	paths["/api/v1/tenants/{tenant}/quotas/{quota}"] = pathItem{
		Get: &operation{
			Tags: []string{"quotas"}, Summary: "Get quota", OperationID: "getQuota",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("quota", "Quota name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Quota.", "QuotaView"),
			}),
		},
		Patch: &operation{
			Tags: []string{"quotas"}, Summary: "Patch quota", OperationID: "updateQuota",
			Parameters:  []parameter{pathParam("tenant", "Tenant name."), pathParam("quota", "Quota name.")},
			RequestBody: jsonBody("QuotaUpdateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Updated.", "QuotaView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"quotas"}, Summary: "Delete quota", OperationID: "deleteQuota",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("quota", "Quota name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}

	// --- jobs (per tenant) ---
	paths["/api/v1/tenants/{tenant}/jobs"] = pathItem{
		Post: &operation{
			Tags: []string{"jobs"}, Summary: "Submit an MLJob", OperationID: "createJob",
			Parameters:  []parameter{pathParam("tenant", "Tenant name.")},
			RequestBody: jsonBody("JobCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Created.", "JobView"),
			}),
		},
		Get: &operation{
			Tags: []string{"jobs"}, Summary: "List jobs for a tenant", OperationID: "listJobs",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Page.", "JobList"),
			}),
		},
	}
	paths["/api/v1/tenants/{tenant}/jobs/{job}"] = pathItem{
		Get: &operation{
			Tags: []string{"jobs"}, Summary: "Get job", OperationID: "getJob",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("job", "Job name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Job.", "JobView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"jobs"}, Summary: "Delete job", OperationID: "deleteJob",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("job", "Job name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}
	paths["/api/v1/tenants/{tenant}/jobs/{job}/cancel"] = pathItem{Post: &operation{
		Tags: []string{"jobs"}, Summary: "Cancel a running job", OperationID: "cancelJob",
		Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("job", "Job name.")},
		Responses: merge(defaultErrors(), map[string]response{
			"200": jsonResp("Cancelled job.", "JobView"),
		}),
	}}

	// --- services (per tenant) ---
	paths["/api/v1/tenants/{tenant}/services"] = pathItem{
		Post: &operation{
			Tags: []string{"services"}, Summary: "Submit an MLService", OperationID: "createMLService",
			Parameters:  []parameter{pathParam("tenant", "Tenant name.")},
			RequestBody: jsonBody("MLServiceCreateInput"),
			Responses: merge(defaultErrors(), map[string]response{
				"201": jsonResp("Created.", "MLServiceView"),
			}),
		},
		Get: &operation{
			Tags: []string{"services"}, Summary: "List services for a tenant", OperationID: "listMLServices",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), limitParam, offsetParam},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Page.", "MLServiceList"),
			}),
		},
	}
	paths["/api/v1/tenants/{tenant}/services/{service}"] = pathItem{
		Get: &operation{
			Tags: []string{"services"}, Summary: "Get service", OperationID: "getMLService",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("service", "Service name.")},
			Responses: merge(defaultErrors(), map[string]response{
				"200": jsonResp("Service.", "MLServiceView"),
			}),
		},
		Delete: &operation{
			Tags: []string{"services"}, Summary: "Delete service", OperationID: "deleteMLService",
			Parameters: []parameter{pathParam("tenant", "Tenant name."), pathParam("service", "Service name.")},
			Responses:  merge(defaultErrors(), map[string]response{"204": noContent}),
		},
	}
	paths["/api/v1/tenants/{tenant}/services/{service}/scale"] = pathItem{Post: &operation{
		Tags: []string{"services"}, Summary: "Scale a service", OperationID: "scaleMLService",
		Parameters:  []parameter{pathParam("tenant", "Tenant name."), pathParam("service", "Service name.")},
		RequestBody: jsonBody("MLServiceScaleInput"),
		Responses: merge(defaultErrors(), map[string]response{
			"200": jsonResp("Scaled service.", "MLServiceView"),
		}),
	}}

	return &document{
		OpenAPI: "3.0.3",
		Info: info{
			Title:       "AxisML Compute API",
			Version:     version,
			Description: "REST API for tenants, resource pools, resource units, quotas, jobs, and services. RFC7807 Problem responses on errors.",
		},
		Servers: []serverEntry{{URL: "/", Description: "Same-origin"}},
		Tags:    tags,
		Paths:   paths,
		Components: componentsBlock{
			Schemas: g.defs,
		},
	}
}
