// openapi-gen renders an OpenAPI 3.0 description of the compute HTTP API
// to docs/openapi.yaml.
//
// Schemas are derived from the same Go request/response structs the runtime
// handlers use, so the spec stays in lock-step with the code. Routes and
// operations are listed explicitly here (single source of truth) rather than
// scraped from the gin router so the file is reviewable.
//
// Run from the component root:
//
//	go run ./cmd/openapi-gen -o docs/openapi.yaml
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"sigs.k8s.io/yaml"

	"github.com/axisml/axisml/components/compute/internal/job"
	"github.com/axisml/axisml/components/compute/internal/quota"
	"github.com/axisml/axisml/components/compute/internal/resourcepool"
	"github.com/axisml/axisml/components/compute/internal/resourceunit"
	"github.com/axisml/axisml/components/compute/internal/server"
	servicemod "github.com/axisml/axisml/components/compute/internal/service"
	"github.com/axisml/axisml/components/compute/internal/tenant"
	apperrors "github.com/axisml/axisml/components/compute/pkg/errors"
)

// defaultVersion is used when -version is not passed. The make target wires
// IMAGE_TAG (which tracks deploy/helm/axisml-system Chart.yaml appVersion)
// through to the flag so generated specs are tagged with the chart version.
const defaultVersion = "0.1.0"

func main() {
	out := flag.String("o", "docs/openapi.yaml", "output path")
	v := flag.String("version", defaultVersion, "info.version field")
	flag.Parse()

	doc := buildDocument(*v)

	yml, err := yaml.Marshal(doc)
	if err != nil {
		fail("marshal: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fail("mkdir: %v", err)
	}
	header := []byte("# Code generated by cmd/openapi-gen. DO NOT EDIT.\n# Regenerate with: make openapi\n")
	if err := os.WriteFile(*out, append(header, yml...), 0o644); err != nil {
		fail("write: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "openapi-gen: "+format+"\n", args...)
	os.Exit(1)
}

// --- OpenAPI 3.0 types (subset we emit) -------------------------------------

type document struct {
	OpenAPI    string              `json:"openapi"`
	Info       info                `json:"info"`
	Servers    []serverEntry       `json:"servers,omitempty"`
	Tags       []tagEntry          `json:"tags,omitempty"`
	Paths      map[string]pathItem `json:"paths"`
	Components componentsBlock     `json:"components"`
}

type info struct {
	Title       string `json:"title"`
	Version     string `json:"version"`
	Description string `json:"description,omitempty"`
}

type serverEntry struct {
	URL         string `json:"url"`
	Description string `json:"description,omitempty"`
}

type tagEntry struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

type pathItem struct {
	Get    *operation `json:"get,omitempty"`
	Post   *operation `json:"post,omitempty"`
	Patch  *operation `json:"patch,omitempty"`
	Delete *operation `json:"delete,omitempty"`
	Put    *operation `json:"put,omitempty"`
}

type operation struct {
	Tags        []string            `json:"tags,omitempty"`
	Summary     string              `json:"summary,omitempty"`
	OperationID string              `json:"operationId,omitempty"`
	Parameters  []parameter         `json:"parameters,omitempty"`
	RequestBody *requestBody        `json:"requestBody,omitempty"`
	Responses   map[string]response `json:"responses"`
}

type parameter struct {
	Name        string  `json:"name"`
	In          string  `json:"in"`
	Required    bool    `json:"required,omitempty"`
	Description string  `json:"description,omitempty"`
	Schema      *schema `json:"schema,omitempty"`
}

type requestBody struct {
	Required bool                 `json:"required,omitempty"`
	Content  map[string]mediaType `json:"content"`
}

type response struct {
	Description string               `json:"description"`
	Content     map[string]mediaType `json:"content,omitempty"`
}

type mediaType struct {
	Schema *schema `json:"schema,omitempty"`
}

type componentsBlock struct {
	Schemas map[string]*schema `json:"schemas"`
}

// schema is a minimal subset of OpenAPI 3.0 schema. Only fields we emit.
type schema struct {
	Ref                  string             `json:"$ref,omitempty"`
	Type                 string             `json:"type,omitempty"`
	Format               string             `json:"format,omitempty"`
	Description          string             `json:"description,omitempty"`
	Required             []string           `json:"required,omitempty"`
	Properties           map[string]*schema `json:"properties,omitempty"`
	Items                *schema            `json:"items,omitempty"`
	AdditionalProperties *schema            `json:"additionalProperties,omitempty"`
	Nullable             bool               `json:"nullable,omitempty"`
	Enum                 []string           `json:"enum,omitempty"`
	Pattern              string             `json:"pattern,omitempty"`
	MinLength            *int               `json:"minLength,omitempty"`
	MaxLength            *int               `json:"maxLength,omitempty"`
	Minimum              *float64           `json:"minimum,omitempty"`
	Maximum              *float64           `json:"maximum,omitempty"`
	MinItems             *int               `json:"minItems,omitempty"`
	MaxItems             *int               `json:"maxItems,omitempty"`
	AllOf                []*schema          `json:"allOf,omitempty"`
}

func ref(name string) *schema { return &schema{Ref: "#/components/schemas/" + name} }

// apiMode controls how a top-level schema's required-list is computed. Inputs
// take their cue from gin `binding` tags; responses treat any field that
// doesn't carry `omitempty` (and isn't a pointer) as always present, which is
// what client codegens want for typed accessors.
//
// Mode propagates only to the root struct's fields. Nested schemas (Kubernetes
// API types, etc.) always use the response/omitempty rule because the same
// component schema may be reached from both an input and an output context,
// and we want one canonical shape per type.
type apiMode int

const (
	responseMode apiMode = iota
	inputMode
)

// Tag names. One source of truth so a typo can't silently split a group.
const (
	tagTenants       = "tenants"
	tagResourcePools = "resource-pools"
	tagResourceUnits = "resource-units"
	tagQuotas        = "quotas"
	tagJobs          = "jobs"
	tagServices      = "services"
	tagSystem        = "system"
)

// --- Stateless OpenAPI builders (lifted out of buildDocument for clarity) ---

func pathParam(name, desc string) parameter {
	return parameter{Name: name, In: "path", Required: true, Description: desc, Schema: &schema{Type: "string"}}
}

func queryParam(name, desc string, sch *schema) parameter {
	return parameter{Name: name, In: "query", Description: desc, Schema: sch}
}

func jsonBody(refName string) *requestBody {
	return &requestBody{
		Required: true,
		Content:  map[string]mediaType{"application/json": {Schema: ref(refName)}},
	}
}

func jsonResp(desc, refName string) response {
	return response{
		Description: desc,
		Content:     map[string]mediaType{"application/json": {Schema: ref(refName)}},
	}
}

func stringResp(desc string) response {
	return response{
		Description: desc,
		Content:     map[string]mediaType{"text/plain": {Schema: &schema{Type: "string"}}},
	}
}

// withErrors returns the standard Problem-bearing error responses with the
// given success codes overlaid. Every domain operation calls this — keeps
// the route table focused on what's unique per route. Codes here must stay
// in lock-step with internal/server/problem.go's statusFor.
func withErrors(success map[string]response) map[string]response {
	out := map[string]response{
		"400":     jsonResp("Validation error.", "Problem"),
		"401":     jsonResp("Unauthorized.", "Problem"),
		"403":     jsonResp("Forbidden.", "Problem"),
		"404":     jsonResp("Not found.", "Problem"),
		"409":     jsonResp("Conflict.", "Problem"),
		"412":     jsonResp("Precondition failed.", "Problem"),
		"422":     jsonResp("Quota exceeded.", "Problem"),
		"503":     jsonResp("Service unavailable.", "Problem"),
		"default": jsonResp("Unexpected error.", "Problem"),
	}
	for k, v := range success {
		out[k] = v
	}
	return out
}

var (
	noContentResp = response{Description: "Deleted (idempotent)."}
	limitParam    = queryParam("limit", "Page size (1–200, default 50).", &schema{Type: "integer", Format: "int32"})
	offsetParam   = queryParam("offset", "Number of items to skip.", &schema{Type: "integer", Format: "int32"})
)

// --- Reflection-based schema generator --------------------------------------

type generator struct {
	defs map[string]*schema
	// inProgress tracks types currently being generated to break cycles.
	inProgress map[reflect.Type]string
}

func newGenerator() *generator {
	return &generator{defs: map[string]*schema{}, inProgress: map[reflect.Type]string{}}
}

// register derives a schema for v and stores it under the provided component
// name (so handlers can reference it as #/components/schemas/<name>). For
// named struct types we call structSchema directly so the slot holds the
// expanded schema rather than a $ref to itself.
func (g *generator) register(name string, v any, mode apiMode) {
	t := reflect.TypeOf(v)
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	g.inProgress[t] = name
	var s *schema
	if ws := wellKnown(t); ws != nil {
		s = ws
	} else if t.Kind() == reflect.Struct {
		s = g.structSchema(t, mode)
	} else {
		s = g.schemaForType(t)
	}
	g.defs[name] = s
	delete(g.inProgress, t)
}

// schemaForType is the workhorse. For named struct types it emits a $ref
// (defining the target lazily) so we get a tidy components/schemas section
// instead of inline duplication. Nested types always use response-mode
// required semantics (see apiMode docs).
func (g *generator) schemaForType(t reflect.Type) *schema {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if s := wellKnown(t); s != nil {
		return s
	}
	switch t.Kind() {
	case reflect.String:
		return &schema{Type: "string"}
	case reflect.Bool:
		return &schema{Type: "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		// Note: uint64 is rendered as int64 since OpenAPI 3.0 has no native
		// unsigned integer type. None of our public structs use uint64; if
		// that changes, consider emitting `format: int64` with a description.
		return &schema{Type: "integer", Format: intFormat(t)}
	case reflect.Float32, reflect.Float64:
		return &schema{Type: "number", Format: floatFormat(t)}
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 { // []byte → base64 string
			return &schema{Type: "string", Format: "byte"}
		}
		return &schema{Type: "array", Items: g.schemaForType(t.Elem())}
	case reflect.Map:
		return &schema{Type: "object", AdditionalProperties: g.schemaForType(t.Elem())}
	case reflect.Struct:
		// Anonymous structs are inlined; named ones become $ref.
		if t.Name() != "" {
			name := componentName(t)
			if existing, ok := g.inProgress[t]; ok {
				return ref(existing)
			}
			if _, defined := g.defs[name]; defined {
				return ref(name)
			}
			g.inProgress[t] = name
			s := g.structSchema(t, responseMode)
			g.defs[name] = s
			delete(g.inProgress, t)
			return ref(name)
		}
		return g.structSchema(t, responseMode)
	case reflect.Interface:
		return &schema{} // free-form
	}
	return &schema{}
}

func (g *generator) structSchema(t reflect.Type, mode apiMode) *schema {
	out := &schema{Type: "object", Properties: map[string]*schema{}}
	var required []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		if f.Anonymous && f.Type.Kind() == reflect.Struct && f.Tag.Get("json") == "" {
			sub := g.structSchema(f.Type, mode)
			for k, v := range sub.Properties {
				out.Properties[k] = v
			}
			required = append(required, sub.Required...)
			continue
		}
		jsonTag := f.Tag.Get("json")
		if jsonTag == "-" {
			continue
		}
		name, opts := splitTag(jsonTag)
		if name == "" {
			name = f.Name
		}
		fs := g.schemaForType(f.Type)
		applyValidators(fs, f.Tag.Get("binding"), f.Type)
		if isPtr(f.Type) {
			if fs.Ref != "" {
				// OpenAPI 3.0 ignores sibling keys next to $ref (fixed in 3.1),
				// so a bare `{$ref, nullable: true}` would silently drop the
				// nullability hint. Wrap in `allOf` to surface it.
				fs = &schema{Nullable: true, AllOf: []*schema{{Ref: fs.Ref}}}
			} else {
				fs.Nullable = true
			}
		}
		out.Properties[name] = fs
		if isFieldRequired(mode, f.Tag.Get("binding"), opts, f.Type) {
			required = append(required, name)
		}
	}
	if len(required) > 0 {
		sort.Strings(required)
		out.Required = required
	}
	return out
}

func splitTag(tag string) (name string, opts []string) {
	parts := strings.Split(tag, ",")
	if len(parts) == 0 {
		return "", nil
	}
	return parts[0], parts[1:]
}

// isFieldRequired decides whether a struct field appears in the schema's
// required list. See apiMode docs for the rationale.
func isFieldRequired(mode apiMode, binding string, jsonOpts []string, t reflect.Type) bool {
	for _, o := range jsonOpts {
		if o == "omitempty" {
			return false
		}
	}
	if isPtr(t) {
		return false
	}
	if mode == responseMode {
		return true
	}
	for _, b := range strings.Split(binding, ",") {
		if strings.TrimSpace(b) == "required" {
			return true
		}
	}
	return false
}

// applyValidators reads the validator/v10 `binding` tag and translates the
// subset we use into OpenAPI schema constraints. Unknown rules are skipped so
// the generator stays forward-compatible with new bindings.
func applyValidators(s *schema, binding string, t reflect.Type) {
	if binding == "" || s == nil {
		return
	}
	for _, raw := range strings.Split(binding, ",") {
		rule := strings.TrimSpace(raw)
		switch {
		case rule == "" || rule == "required":
			// Required is handled separately via isFieldRequired.
		case rule == "axisml_name", rule == "axisml_resource_unit":
			applyAxisMLNamePattern(s)
		case strings.HasPrefix(rule, "min="):
			applySize(s, t, rule[len("min="):], minBound)
		case strings.HasPrefix(rule, "max="):
			applySize(s, t, rule[len("max="):], maxBound)
		case strings.HasPrefix(rule, "len="):
			applySize(s, t, rule[len("len="):], exactBound)
		case strings.HasPrefix(rule, "gte="):
			if v, ok := parseFloat(rule[len("gte="):]); ok {
				s.Minimum = &v
			}
		case strings.HasPrefix(rule, "lte="):
			if v, ok := parseFloat(rule[len("lte="):]); ok {
				s.Maximum = &v
			}
		}
	}
}

type bound int

const (
	minBound bound = iota
	maxBound
	exactBound
)

// applySize maps validator/v10 size constraints (min/max/len) to the right
// OpenAPI keyword for the field's Go type: minLength on strings, minItems on
// slices/arrays/maps, minimum on numbers.
func applySize(s *schema, t reflect.Type, raw string, b bound) {
	n, ok := parseInt(raw)
	if !ok {
		return
	}
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.String:
		applyLengthBound(s, n, b)
	case reflect.Slice, reflect.Array, reflect.Map:
		applyItemsBound(s, n, b)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		f := float64(n)
		applyNumberBound(s, f, b)
	}
}

func applyLengthBound(s *schema, n int, b bound) {
	switch b {
	case minBound:
		s.MinLength = &n
	case maxBound:
		s.MaxLength = &n
	case exactBound:
		s.MinLength = &n
		s.MaxLength = &n
	}
}

func applyItemsBound(s *schema, n int, b bound) {
	switch b {
	case minBound:
		s.MinItems = &n
	case maxBound:
		s.MaxItems = &n
	case exactBound:
		s.MinItems = &n
		s.MaxItems = &n
	}
}

func applyNumberBound(s *schema, f float64, b bound) {
	switch b {
	case minBound:
		s.Minimum = &f
	case maxBound:
		s.Maximum = &f
	case exactBound:
		s.Minimum = &f
		s.Maximum = &f
	}
}

// applyAxisMLNamePattern surfaces the AxisML §6.1 name policy as schema
// constraints. The regex is duplicated rather than imported because the
// generator's contract is "render whatever clients need to send"; clients
// don't import strutil.
const axisMLNamePattern = "^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])?$"

func applyAxisMLNamePattern(s *schema) {
	if s == nil || s.Type != "string" {
		return
	}
	s.Pattern = axisMLNamePattern
	minLen := 3
	maxLen := 40
	s.MinLength = &minLen
	s.MaxLength = &maxLen
}

func parseInt(s string) (int, bool) {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		return 0, false
	}
	return n, true
}

func parseFloat(s string) (float64, bool) {
	f, err := strconv.ParseFloat(strings.TrimSpace(s), 64)
	if err != nil {
		return 0, false
	}
	return f, true
}

func isPtr(t reflect.Type) bool { return t.Kind() == reflect.Pointer }

func intFormat(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Int32, reflect.Uint32, reflect.Int16, reflect.Uint16, reflect.Int8, reflect.Uint8:
		return "int32"
	case reflect.Int64, reflect.Uint64:
		return "int64"
	}
	return ""
}

func floatFormat(t reflect.Type) string {
	if t.Kind() == reflect.Float32 {
		return "float"
	}
	return "double"
}

// componentName produces a stable, human-readable name for a Go type. For the
// three operator API packages we pull the operator name from the path so
// MLJob/MLService/Tenant types don't collide on a shared "v1alpha1" prefix.
// For other versioned packages (corev1, metav1, …) we qualify the version
// segment with the parent so e.g. core/v1 → Corev1Container instead of every
// v1 package collapsing to V1*.
func componentName(t reflect.Type) string {
	pkg := t.PkgPath()
	if prefix, ok := operatorAPIPrefix(pkg); ok {
		// Avoid e.g. "MLJobMLJobSpec" — keep just "MLJobSpec" if the type name
		// already starts with the prefix.
		if strings.HasPrefix(t.Name(), prefix) {
			return t.Name()
		}
		return prefix + t.Name()
	}
	// Compute's own service package is named "service"; collapse to MLService
	// so it reads as a noun rather than a generic word.
	if strings.HasSuffix(pkg, "/internal/service") {
		return "MLService" + t.Name()
	}
	parts := strings.Split(pkg, "/")
	last := parts[len(parts)-1]
	if last == "" {
		return t.Name()
	}
	if isVersionSegment(last) && len(parts) >= 2 {
		last = parts[len(parts)-2] + last
	}
	return capitalize(last) + t.Name()
}

// isVersionSegment reports whether s looks like a Kubernetes-style API
// version (v1, v1alpha1, v2beta1, …).
func isVersionSegment(s string) bool {
	if len(s) < 2 || s[0] != 'v' {
		return false
	}
	return s[1] >= '0' && s[1] <= '9'
}

// operatorAPIPrefix maps the three operator API packages to a prefix that
// includes the operator name. The path looks like
// ".../components/operators/<op>-operator/api/v1alpha1".
func operatorAPIPrefix(pkg string) (string, bool) {
	const opRoot = "components/operators/"
	i := strings.Index(pkg, opRoot)
	if i < 0 {
		return "", false
	}
	rest := pkg[i+len(opRoot):]
	parts := strings.Split(rest, "/")
	if len(parts) < 1 {
		return "", false
	}
	op := strings.TrimSuffix(parts[0], "-operator")
	switch op {
	case "mljob":
		return "MLJob", true
	case "mlservice":
		return "MLService", true
	case "tenant":
		return "Tenant", true
	}
	return "", false
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// Type-identity comparisons avoid stringly-typed package-path checks. These
// are pulled out so the switch below stays a flat type table.
var (
	timeType         = reflect.TypeOf(time.Time{})
	uuidType         = reflect.TypeOf(uuid.UUID{})
	quantityType     = reflect.TypeOf(resource.Quantity{})
	datatypesJSON    = reflect.TypeOf(datatypes.JSON{})
	resourceListType = reflect.TypeOf(corev1.ResourceList{})
	apperrorsCode    = reflect.TypeOf(apperrors.Code(""))
)

// wellKnown maps Go types that don't have a useful struct-reflective shape
// (or that we want to render with a specific OpenAPI flavor) to a fixed
// schema. Returning nil falls through to the default reflection path.
func wellKnown(t reflect.Type) *schema {
	switch t {
	case timeType:
		return &schema{Type: "string", Format: "date-time"}
	case uuidType:
		return &schema{Type: "string", Format: "uuid"}
	case quantityType:
		return &schema{
			Type:        "string",
			Description: "Kubernetes resource.Quantity (e.g. \"500m\", \"2Gi\", \"4\").",
		}
	case datatypesJSON:
		return &schema{Type: "object", Description: "Free-form JSON object."}
	case resourceListType:
		return &schema{
			Type: "object",
			AdditionalProperties: &schema{
				Type:        "string",
				Description: "Kubernetes resource.Quantity.",
			},
			Description: "Map of resource name (cpu, memory, nvidia.com/gpu, …) to resource.Quantity.",
		}
	case apperrorsCode:
		// Named string with a closed set of values. Surface the enum so
		// client codegens emit a typed accessor.
		return &schema{
			Type:        "string",
			Description: "Discrete business error class.",
			Enum:        apperrors.AllCodes(),
		}
	}
	// metav1.Duration has a single String-marshalling Duration field; render it
	// as a string instead of an object.
	if t.Kind() == reflect.Struct && t.PkgPath() == "k8s.io/apimachinery/pkg/apis/meta/v1" && t.Name() == "Duration" {
		return &schema{Type: "string", Description: "Go duration string (e.g. \"30s\", \"5m\")."}
	}
	// runtime.RawExtension exposes only json:"-" fields, so reflection yields
	// an empty object. Render it as free-form so clients know it's opaque.
	if t.Kind() == reflect.Struct && t.PkgPath() == "k8s.io/apimachinery/pkg/runtime" && t.Name() == "RawExtension" {
		return &schema{Type: "object", Description: "Embedded Kubernetes resource (free-form JSON)."}
	}
	return nil
}

// --- Document construction --------------------------------------------------

func buildDocument(version string) *document {
	g := newGenerator()

	// Core component schemas (referenced from operations).
	g.register("Problem", server.Problem{}, responseMode)
	g.register("TenantCreateInput", tenant.CreateInput{}, inputMode)
	g.register("TenantUpdateInput", tenant.UpdateInput{}, inputMode)
	g.register("TenantView", tenant.View{}, responseMode)
	g.register("ResourcepoolCreateInput", resourcepool.CreateInput{}, inputMode)
	g.register("ResourcepoolUpdateInput", resourcepool.UpdateInput{}, inputMode)
	g.register("ResourcepoolView", resourcepool.View{}, responseMode)
	g.register("ResourceunitCreateInput", resourceunit.CreateInput{}, inputMode)
	g.register("ResourceunitUpdateInput", resourceunit.UpdateInput{}, inputMode)
	g.register("ResourceunitView", resourceunit.View{}, responseMode)
	g.register("QuotaCreateInput", quota.CreateInput{}, inputMode)
	g.register("QuotaUpdateInput", quota.UpdateInput{}, inputMode)
	g.register("QuotaView", quota.View{}, responseMode)
	g.register("JobCreateInput", job.CreateInput{}, inputMode)
	g.register("JobView", job.View{}, responseMode)
	g.register("MLServiceCreateInput", servicemod.CreateInput{}, inputMode)
	g.register("MLServiceScaleInput", servicemod.ScaleInput{}, inputMode)
	g.register("MLServiceView", servicemod.View{}, responseMode)

	// Generic list envelope: {items: [], total: int}. We emit one envelope per
	// resource so $ref to the right item type is preserved.
	listEnvelope := func(itemRef string) *schema {
		return &schema{
			Type:     "object",
			Required: []string{"items", "total"},
			Properties: map[string]*schema{
				"items": {Type: "array", Items: ref(itemRef)},
				"total": {Type: "integer", Format: "int64"},
			},
		}
	}
	g.defs["TenantList"] = listEnvelope("TenantView")
	g.defs["ResourcepoolList"] = listEnvelope("ResourcepoolView")
	g.defs["ResourceunitList"] = listEnvelope("ResourceunitView")
	g.defs["QuotaList"] = listEnvelope("QuotaView")
	g.defs["JobList"] = listEnvelope("JobView")
	g.defs["MLServiceList"] = listEnvelope("MLServiceView")

	tags := []tagEntry{
		{Name: tagTenants, Description: "Tenant CRUD and lifecycle."},
		{Name: tagResourcePools, Description: "Cluster-scoped resource pool registry."},
		{Name: tagResourceUnits, Description: "Reusable CPU/GPU/memory recipes scoped to a pool."},
		{Name: tagQuotas, Description: "Per-(tenant, pool) ElasticQuota records."},
		{Name: tagJobs, Description: "MLJob CRUD per tenant."},
		{Name: tagServices, Description: "MLService CRUD per tenant."},
		{Name: tagSystem, Description: "Liveness and readiness probes."},
	}

	tenantParam := pathParam("tenant", "Tenant name.")
	poolParam := pathParam("pool", "Resource pool name.")
	unitParam := pathParam("unit", "Resource unit name.")
	quotaParam := pathParam("quota", "Quota name.")
	jobParam := pathParam("job", "Job name.")
	serviceParam := pathParam("service", "Service name.")

	paths := map[string]pathItem{}

	// system probes
	paths["/healthz"] = pathItem{Get: &operation{
		Tags: []string{tagSystem}, Summary: "Liveness probe", OperationID: "healthz",
		Responses: map[string]response{"200": stringResp("ok")},
	}}
	paths["/readyz"] = pathItem{Get: &operation{
		Tags: []string{tagSystem}, Summary: "Readiness probe", OperationID: "readyz",
		Responses: map[string]response{
			"200": stringResp("ok"),
			"503": stringResp("dependency not yet ready"),
		},
	}}

	// tenants
	paths["/api/v1/tenants"] = pathItem{
		Post: &operation{
			Tags: []string{tagTenants}, Summary: "Create a tenant", OperationID: "createTenant",
			RequestBody: jsonBody("TenantCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Tenant created.", "TenantView")}),
		},
		Get: &operation{
			Tags: []string{tagTenants}, Summary: "List tenants", OperationID: "listTenants",
			Parameters: []parameter{limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Tenant page.", "TenantList")}),
		},
	}
	paths["/api/v1/tenants/{tenant}"] = pathItem{
		Get: &operation{
			Tags: []string{tagTenants}, Summary: "Get tenant", OperationID: "getTenant",
			Parameters: []parameter{tenantParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Tenant.", "TenantView")}),
		},
		Patch: &operation{
			Tags: []string{tagTenants}, Summary: "Patch tenant", OperationID: "updateTenant",
			Parameters:  []parameter{tenantParam},
			RequestBody: jsonBody("TenantUpdateInput"),
			Responses:   withErrors(map[string]response{"200": jsonResp("Updated tenant.", "TenantView")}),
		},
		Delete: &operation{
			Tags: []string{tagTenants}, Summary: "Delete tenant", OperationID: "deleteTenant",
			Parameters: []parameter{tenantParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}
	paths["/api/v1/tenants/{tenant}/suspend"] = pathItem{Post: &operation{
		Tags: []string{tagTenants}, Summary: "Suspend tenant", OperationID: "suspendTenant",
		Parameters: []parameter{tenantParam},
		Responses:  withErrors(map[string]response{"200": jsonResp("Suspended.", "TenantView")}),
	}}
	paths["/api/v1/tenants/{tenant}/unsuspend"] = pathItem{Post: &operation{
		Tags: []string{tagTenants}, Summary: "Unsuspend tenant", OperationID: "unsuspendTenant",
		Parameters: []parameter{tenantParam},
		Responses:  withErrors(map[string]response{"200": jsonResp("Unsuspended.", "TenantView")}),
	}}

	// resource pools
	paths["/api/v1/resource-pools"] = pathItem{
		Post: &operation{
			Tags: []string{tagResourcePools}, Summary: "Create a resource pool", OperationID: "createResourcePool",
			RequestBody: jsonBody("ResourcepoolCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Created.", "ResourcepoolView")}),
		},
		Get: &operation{
			Tags: []string{tagResourcePools}, Summary: "List resource pools", OperationID: "listResourcePools",
			Parameters: []parameter{limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Page.", "ResourcepoolList")}),
		},
	}
	paths["/api/v1/resource-pools/{pool}"] = pathItem{
		Get: &operation{
			Tags: []string{tagResourcePools}, Summary: "Get resource pool", OperationID: "getResourcePool",
			Parameters: []parameter{poolParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Resource pool.", "ResourcepoolView")}),
		},
		Patch: &operation{
			Tags: []string{tagResourcePools}, Summary: "Patch resource pool", OperationID: "updateResourcePool",
			Parameters:  []parameter{poolParam},
			RequestBody: jsonBody("ResourcepoolUpdateInput"),
			Responses:   withErrors(map[string]response{"200": jsonResp("Updated.", "ResourcepoolView")}),
		},
		Delete: &operation{
			Tags: []string{tagResourcePools}, Summary: "Delete resource pool", OperationID: "deleteResourcePool",
			Parameters: []parameter{poolParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}

	// resource units (under a pool)
	paths["/api/v1/resource-pools/{pool}/resource-units"] = pathItem{
		Post: &operation{
			Tags: []string{tagResourceUnits}, Summary: "Create a resource unit", OperationID: "createResourceUnit",
			Parameters:  []parameter{poolParam},
			RequestBody: jsonBody("ResourceunitCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Created.", "ResourceunitView")}),
		},
		Get: &operation{
			Tags: []string{tagResourceUnits}, Summary: "List resource units in a pool", OperationID: "listResourceUnits",
			Parameters: []parameter{poolParam, limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Page.", "ResourceunitList")}),
		},
	}
	paths["/api/v1/resource-pools/{pool}/resource-units/{unit}"] = pathItem{
		Get: &operation{
			Tags: []string{tagResourceUnits}, Summary: "Get resource unit", OperationID: "getResourceUnit",
			Parameters: []parameter{poolParam, unitParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Resource unit.", "ResourceunitView")}),
		},
		Patch: &operation{
			Tags: []string{tagResourceUnits}, Summary: "Patch resource unit", OperationID: "updateResourceUnit",
			Parameters:  []parameter{poolParam, unitParam},
			RequestBody: jsonBody("ResourceunitUpdateInput"),
			Responses:   withErrors(map[string]response{"200": jsonResp("Updated.", "ResourceunitView")}),
		},
		Delete: &operation{
			Tags: []string{tagResourceUnits}, Summary: "Delete resource unit", OperationID: "deleteResourceUnit",
			Parameters: []parameter{poolParam, unitParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}

	// quotas (per tenant)
	paths["/api/v1/tenants/{tenant}/quotas"] = pathItem{
		Post: &operation{
			Tags: []string{tagQuotas}, Summary: "Create a quota", OperationID: "createQuota",
			Parameters:  []parameter{tenantParam},
			RequestBody: jsonBody("QuotaCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Created.", "QuotaView")}),
		},
		Get: &operation{
			Tags: []string{tagQuotas}, Summary: "List quotas for a tenant", OperationID: "listQuotas",
			Parameters: []parameter{tenantParam, limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Page.", "QuotaList")}),
		},
	}
	paths["/api/v1/tenants/{tenant}/quotas/{quota}"] = pathItem{
		Get: &operation{
			Tags: []string{tagQuotas}, Summary: "Get quota", OperationID: "getQuota",
			Parameters: []parameter{tenantParam, quotaParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Quota.", "QuotaView")}),
		},
		Patch: &operation{
			Tags: []string{tagQuotas}, Summary: "Patch quota", OperationID: "updateQuota",
			Parameters:  []parameter{tenantParam, quotaParam},
			RequestBody: jsonBody("QuotaUpdateInput"),
			Responses:   withErrors(map[string]response{"200": jsonResp("Updated.", "QuotaView")}),
		},
		Delete: &operation{
			Tags: []string{tagQuotas}, Summary: "Delete quota", OperationID: "deleteQuota",
			Parameters: []parameter{tenantParam, quotaParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}

	// jobs (per tenant)
	paths["/api/v1/tenants/{tenant}/jobs"] = pathItem{
		Post: &operation{
			Tags: []string{tagJobs}, Summary: "Submit an MLJob", OperationID: "createJob",
			Parameters:  []parameter{tenantParam},
			RequestBody: jsonBody("JobCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Created.", "JobView")}),
		},
		Get: &operation{
			Tags: []string{tagJobs}, Summary: "List jobs for a tenant", OperationID: "listJobs",
			Parameters: []parameter{tenantParam, limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Page.", "JobList")}),
		},
	}
	paths["/api/v1/tenants/{tenant}/jobs/{job}"] = pathItem{
		Get: &operation{
			Tags: []string{tagJobs}, Summary: "Get job", OperationID: "getJob",
			Parameters: []parameter{tenantParam, jobParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Job.", "JobView")}),
		},
		Delete: &operation{
			Tags: []string{tagJobs}, Summary: "Delete job", OperationID: "deleteJob",
			Parameters: []parameter{tenantParam, jobParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}
	paths["/api/v1/tenants/{tenant}/jobs/{job}/cancel"] = pathItem{Post: &operation{
		Tags: []string{tagJobs}, Summary: "Cancel a running job", OperationID: "cancelJob",
		Parameters: []parameter{tenantParam, jobParam},
		Responses:  withErrors(map[string]response{"200": jsonResp("Cancelled job.", "JobView")}),
	}}

	// services (per tenant)
	paths["/api/v1/tenants/{tenant}/services"] = pathItem{
		Post: &operation{
			Tags: []string{tagServices}, Summary: "Submit an MLService", OperationID: "createMLService",
			Parameters:  []parameter{tenantParam},
			RequestBody: jsonBody("MLServiceCreateInput"),
			Responses:   withErrors(map[string]response{"201": jsonResp("Created.", "MLServiceView")}),
		},
		Get: &operation{
			Tags: []string{tagServices}, Summary: "List services for a tenant", OperationID: "listMLServices",
			Parameters: []parameter{tenantParam, limitParam, offsetParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Page.", "MLServiceList")}),
		},
	}
	paths["/api/v1/tenants/{tenant}/services/{service}"] = pathItem{
		Get: &operation{
			Tags: []string{tagServices}, Summary: "Get service", OperationID: "getMLService",
			Parameters: []parameter{tenantParam, serviceParam},
			Responses:  withErrors(map[string]response{"200": jsonResp("Service.", "MLServiceView")}),
		},
		Delete: &operation{
			Tags: []string{tagServices}, Summary: "Delete service", OperationID: "deleteMLService",
			Parameters: []parameter{tenantParam, serviceParam},
			Responses:  withErrors(map[string]response{"204": noContentResp}),
		},
	}
	paths["/api/v1/tenants/{tenant}/services/{service}/scale"] = pathItem{Post: &operation{
		Tags: []string{tagServices}, Summary: "Scale a service", OperationID: "scaleMLService",
		Parameters:  []parameter{tenantParam, serviceParam},
		RequestBody: jsonBody("MLServiceScaleInput"),
		Responses:   withErrors(map[string]response{"200": jsonResp("Scaled service.", "MLServiceView")}),
	}}

	return &document{
		OpenAPI: "3.0.3",
		Info: info{
			Title:       "AxisML Compute API",
			Version:     version,
			Description: "REST API for tenants, resource pools, resource units, quotas, jobs, and services. RFC7807 Problem responses on errors.",
		},
		Servers: []serverEntry{{URL: "/", Description: "Same-origin"}},
		Tags:    tags,
		Paths:   paths,
		Components: componentsBlock{
			Schemas: g.defs,
		},
	}
}
