// Code generated by hand to mirror what controller-gen would produce.
// Regenerate with `controller-gen object paths=./...` once the toolchain is wired in.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Backend) DeepCopyInto(out *Backend) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

func (in *Backend) DeepCopy() *Backend {
	if in == nil {
		return nil
	}
	out := new(Backend)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointAuthJWTConfig) DeepCopyInto(out *EndpointAuthJWTConfig) { *out = *in }
func (in *EndpointAuthJWTConfig) DeepCopy() *EndpointAuthJWTConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointAuthJWTConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointAuth) DeepCopyInto(out *EndpointAuth) {
	*out = *in
	if in.JWT != nil {
		out.JWT = in.JWT.DeepCopy()
	}
}

func (in *EndpointAuth) DeepCopy() *EndpointAuth {
	if in == nil {
		return nil
	}
	out := new(EndpointAuth)
	in.DeepCopyInto(out)
	return out
}

func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	if in.Auth != nil {
		out.Auth = in.Auth.DeepCopy()
	}
}

func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendMember) DeepCopyInto(out *BackendMember) { *out = *in }
func (in *BackendMember) DeepCopy() *BackendMember {
	if in == nil {
		return nil
	}
	out := new(BackendMember)
	in.DeepCopyInto(out)
	return out
}

func (in *MLTrafficPolicySpec) DeepCopyInto(out *MLTrafficPolicySpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.Backends != nil {
		out.Backends = make([]BackendMember, len(in.Backends))
		copy(out.Backends, in.Backends)
	}
}

func (in *MLTrafficPolicySpec) DeepCopy() *MLTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MLTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendStatus) DeepCopyInto(out *BackendStatus) { *out = *in }
func (in *BackendStatus) DeepCopy() *BackendStatus {
	if in == nil {
		return nil
	}
	out := new(BackendStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MLTrafficPolicyStatus) DeepCopyInto(out *MLTrafficPolicyStatus) {
	*out = *in
	if in.Backends != nil {
		out.Backends = make([]BackendStatus, len(in.Backends))
		copy(out.Backends, in.Backends)
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *MLTrafficPolicyStatus) DeepCopy() *MLTrafficPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MLTrafficPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MLTrafficPolicy) DeepCopyInto(out *MLTrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MLTrafficPolicy) DeepCopy() *MLTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(MLTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *MLTrafficPolicy) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *MLTrafficPolicyList) DeepCopyInto(out *MLTrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]MLTrafficPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *MLTrafficPolicyList) DeepCopy() *MLTrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(MLTrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *MLTrafficPolicyList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}
