{{- if and .Values.operators.enabled .Values.operators.tenantOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axisml.fullname" . }}-tenant-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "tenant-operator") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "axisml.componentSelectorLabels" (dict "context" . "component" "tenant-operator") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axisml.componentLabels" (dict "context" . "component" "tenant-operator") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axisml.fullname" . }}-tenant-operator
      containers:
        - name: tenant-operator
          image: {{ include "axisml.image" (dict "imageRoot" .Values.operators.tenantOperator.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.operators.tenantOperator.image.pullPolicy }}
          resources:
            {{- toYaml .Values.operators.tenantOperator.resources | nindent 12 }}
{{- end }}
