{{- if and .Values.operators.enabled .Values.operators.tenantOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-tenant-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "tenant-operator") | nindent 4 }}
{{- end }}
