// Code generated by hand to mirror what controller-gen would produce.
// Regenerate with `controller-gen object paths=./...` once the toolchain is wired in.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *Backend) DeepCopyInto(out *Backend) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

func (in *Backend) DeepCopy() *Backend {
	if in == nil {
		return nil
	}
	out := new(Backend)
	in.DeepCopyInto(out)
	return out
}

func (in *Scheduling) DeepCopyInto(out *Scheduling) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = make(map[string]string, len(in.NodeSelector))
		for k, v := range in.NodeSelector {
			out.NodeSelector[k] = v
		}
	}
	if in.Tolerations != nil {
		out.Tolerations = make([]corev1.Toleration, len(in.Tolerations))
		for i := range in.Tolerations {
			in.Tolerations[i].DeepCopyInto(&out.Tolerations[i])
		}
	}
}

func (in *Scheduling) DeepCopy() *Scheduling {
	if in == nil {
		return nil
	}
	out := new(Scheduling)
	in.DeepCopyInto(out)
	return out
}

func (in *ModelRef) DeepCopyInto(out *ModelRef) {
	*out = *in
}

func (in *ModelRef) DeepCopy() *ModelRef {
	if in == nil {
		return nil
	}
	out := new(ModelRef)
	in.DeepCopyInto(out)
	return out
}

func (in *PodPort) DeepCopyInto(out *PodPort) {
	*out = *in
}

func (in *PodPort) DeepCopy() *PodPort {
	if in == nil {
		return nil
	}
	out := new(PodPort)
	in.DeepCopyInto(out)
	return out
}

func (in *PodTemplate) DeepCopyInto(out *PodTemplate) {
	*out = *in
	if in.Command != nil {
		out.Command = append([]string(nil), in.Command...)
	}
	if in.Args != nil {
		out.Args = append([]string(nil), in.Args...)
	}
	if in.Env != nil {
		out.Env = make([]corev1.EnvVar, len(in.Env))
		for i := range in.Env {
			in.Env[i].DeepCopyInto(&out.Env[i])
		}
	}
	if in.EnvFrom != nil {
		out.EnvFrom = make([]corev1.EnvFromSource, len(in.EnvFrom))
		for i := range in.EnvFrom {
			in.EnvFrom[i].DeepCopyInto(&out.EnvFrom[i])
		}
	}
	if in.Ports != nil {
		out.Ports = make([]PodPort, len(in.Ports))
		copy(out.Ports, in.Ports)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *PodTemplate) DeepCopy() *PodTemplate {
	if in == nil {
		return nil
	}
	out := new(PodTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleSpec) DeepCopyInto(out *RoleSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

func (in *RoleSpec) DeepCopy() *RoleSpec {
	if in == nil {
		return nil
	}
	out := new(RoleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RunPolicy) DeepCopyInto(out *RunPolicy) {
	*out = *in
	if in.ProgressDeadlineSeconds != nil {
		out.ProgressDeadlineSeconds = new(int32)
		*out.ProgressDeadlineSeconds = *in.ProgressDeadlineSeconds
	}
}

func (in *RunPolicy) DeepCopy() *RunPolicy {
	if in == nil {
		return nil
	}
	out := new(RunPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteAuthJWTConfig) DeepCopyInto(out *RouteAuthJWTConfig) { *out = *in }
func (in *RouteAuthJWTConfig) DeepCopy() *RouteAuthJWTConfig {
	if in == nil {
		return nil
	}
	out := new(RouteAuthJWTConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteAuthAPIKeyConfig) DeepCopyInto(out *RouteAuthAPIKeyConfig) { *out = *in }
func (in *RouteAuthAPIKeyConfig) DeepCopy() *RouteAuthAPIKeyConfig {
	if in == nil {
		return nil
	}
	out := new(RouteAuthAPIKeyConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteAuth) DeepCopyInto(out *RouteAuth) {
	*out = *in
	if in.JWT != nil {
		out.JWT = in.JWT.DeepCopy()
	}
	if in.APIKey != nil {
		out.APIKey = in.APIKey.DeepCopy()
	}
}

func (in *RouteAuth) DeepCopy() *RouteAuth {
	if in == nil {
		return nil
	}
	out := new(RouteAuth)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteRateLimit) DeepCopyInto(out *RouteRateLimit) { *out = *in }
func (in *RouteRateLimit) DeepCopy() *RouteRateLimit {
	if in == nil {
		return nil
	}
	out := new(RouteRateLimit)
	in.DeepCopyInto(out)
	return out
}

func (in *Route) DeepCopyInto(out *Route) {
	*out = *in
	if in.Auth != nil {
		out.Auth = in.Auth.DeepCopy()
	}
	if in.RateLimit != nil {
		out.RateLimit = in.RateLimit.DeepCopy()
	}
}

func (in *Route) DeepCopy() *Route {
	if in == nil {
		return nil
	}
	out := new(Route)
	in.DeepCopyInto(out)
	return out
}

func (in *MLServiceSpec) DeepCopyInto(out *MLServiceSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	out.ModelRef = in.ModelRef
	if in.Roles != nil {
		out.Roles = make([]RoleSpec, len(in.Roles))
		for i := range in.Roles {
			in.Roles[i].DeepCopyInto(&out.Roles[i])
		}
	}
	in.RunPolicy.DeepCopyInto(&out.RunPolicy)
	if in.Route != nil {
		out.Route = in.Route.DeepCopy()
	}
}

func (in *MLServiceSpec) DeepCopy() *MLServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MLServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RoleStatus) DeepCopyInto(out *RoleStatus) { *out = *in }
func (in *RoleStatus) DeepCopy() *RoleStatus {
	if in == nil {
		return nil
	}
	out := new(RoleStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MLServiceStatus) DeepCopyInto(out *MLServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.Roles != nil {
		out.Roles = make([]RoleStatus, len(in.Roles))
		copy(out.Roles, in.Roles)
	}
}

func (in *MLServiceStatus) DeepCopy() *MLServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MLServiceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *MLService) DeepCopyInto(out *MLService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *MLService) DeepCopy() *MLService {
	if in == nil {
		return nil
	}
	out := new(MLService)
	in.DeepCopyInto(out)
	return out
}

func (in *MLService) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *MLServiceList) DeepCopyInto(out *MLServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]MLService, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *MLServiceList) DeepCopy() *MLServiceList {
	if in == nil {
		return nil
	}
	out := new(MLServiceList)
	in.DeepCopyInto(out)
	return out
}

func (in *MLServiceList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}
