// Generates src/api/mock/examples.gen.ts from the whole-object `example`s in the
// platform OpenAPI spec (axisml-platform/docs/apis/platform.yaml). Those examples
// are authored on the Go DTOs (see axisml-platform/backend/cmd/openapi-gen/
// examples_*.go) and are the single source of truth for the in-browser mock
// fixtures — so the demo data can never drift from the API contract.
//
// Run with `pnpm run gen:mock` (also chained after gen:api). Keyed by the
// OpenAPI schema name (e.g. "MLService", "JobList"); read back in data.ts via
// the typed `ex<T>(name)` helper.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { load } from "js-yaml";

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, "../../docs/apis/platform.yaml");
const outPath = resolve(here, "../src/api/mock/examples.gen.ts");

const doc = load(readFileSync(specPath, "utf8"));
const schemas = doc?.components?.schemas ?? {};

const entries = Object.entries(schemas)
  .filter(([, schema]) => schema && schema.example !== undefined)
  .sort(([a], [b]) => a.localeCompare(b));

if (entries.length === 0) {
  throw new Error(`gen-mock: no schema examples found in ${specPath}`);
}

const body = entries
  .map(([name, schema]) => `  ${JSON.stringify(name)}: ${JSON.stringify(schema.example, null, 2).replace(/\n/g, "\n  ")},`)
  .join("\n");

const out = `/* eslint-disable */
// AUTO-GENERATED by scripts/gen-mock.mjs from ../../../docs/apis/platform.yaml.
// DO NOT EDIT. Regenerate with: pnpm run gen:mock (or make -C axisml-platform frontend-gen-mock).
//
// Whole-object examples lifted from the OpenAPI spec's component schemas, keyed
// by schema name. These back the in-browser mock (VITE_USE_MOCK_API); the
// authoring lives on the Go DTOs, so fixtures stay in lock-step with the contract.

export const examples: Record<string, unknown> = {
${body}
};

/** Typed accessor: ex<Job>("Job"). Throws if the schema carries no example. */
export function ex<T>(name: string): T {
  const value = examples[name];
  if (value === undefined) {
    throw new Error(\`mock example missing for schema "\${name}" — run pnpm run gen:mock\`);
  }
  return structuredClone(value) as T;
}
`;

writeFileSync(outPath, out);
console.log(`gen-mock: wrote ${entries.length} examples → ${outPath}`);
