{{- if and .Values.computeService.enabled .Values.computeService.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "axisml.fullname" . }}-compute-service
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "compute-service") | nindent 4 }}
    {{- with .Values.computeService.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "axisml.componentSelectorLabels" (dict "context" . "component" "compute-service") | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.computeService.serviceMonitor.interval | default "30s" }}
{{- end }}
