{{- if .Values.operators.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "operator") | nindent 4 }}
{{- end }}
