{{- if .Values.compute.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-compute
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "compute") | nindent 4 }}
{{- end }}
