{{- if .Values.platform.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axisml.fullname" . }}-platform
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "platform") | nindent 4 }}
data:
  ML_CLUSTER_MANAGER_URL: "http://{{ .Values.system.clusterManager.name }}.{{ .Values.system.namespace }}:{{ .Values.system.clusterManager.port }}"
  ML_COMPUTE_URL: "http://{{ .Values.system.computeService.name }}.{{ .Values.system.namespace }}:{{ .Values.system.computeService.port }}"
  ML_ARTIFACTS_URL: "http://{{ .Values.system.artifactHub.name }}.{{ .Values.system.namespace }}:{{ .Values.system.artifactHub.port }}"
  {{- range $key, $value := .Values.platform.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
