{{- if .Values.computeOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-compute-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "compute-operator") | nindent 4 }}
{{- end }}
