{{- if and .Values.operators.enabled .Values.operators.mljobOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axisml.fullname" . }}-mljob-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "mljob-operator") | nindent 4 }}
{{- end }}
