{{- if and .Values.operators.enabled .Values.operators.mljobOperator.enabled .Values.operators.mljobOperator.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "axisml.fullname" . }}-mljob-operator-leaderelection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "mljob-operator") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "axisml.fullname" . }}-mljob-operator-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ include "axisml.fullname" . }}-mljob-operator
    namespace: {{ .Release.Namespace }}
{{- end }}
