{{- if and .Values.operators.enabled .Values.operators.mlserviceOperator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axisml.fullname" . }}-mlservice-operator
  labels:
    {{- include "axisml.componentLabels" (dict "context" . "component" "mlservice-operator") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "axisml.componentSelectorLabels" (dict "context" . "component" "mlservice-operator") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axisml.componentLabels" (dict "context" . "component" "mlservice-operator") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axisml.fullname" . }}-mlservice-operator
      containers:
        - name: mlservice-operator
          image: {{ include "axisml.image" (dict "imageRoot" .Values.operators.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.operators.image.pullPolicy }}
          args:
            - mlservice-operator
            - "--leader-elect=true"
            - "--metrics-bind-address=:8080"
            - "--health-probe-bind-address=:8081"
          ports:
            - name: metrics
              containerPort: 8080
            - name: probes
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operators.mlserviceOperator.resources | nindent 12 }}
{{- end }}
